// Package feedback implements D5 fix-outcome learning for LEVEE's
// recommendation engine.
//
// The FeedbackLearner consumes FixOutcome records produced by the executor
// after a remediation attempt, persists them as FeedbackRecords, and distills
// them into FixPattern and HistoricalIncident entries that are fed back into
// the parent recommend.KnowledgeBase. Over time the knowledge base therefore
// accumulates both successful patterns (so future diagnoses can suggest them
// again) and failure signals (so patterns that repeatedly fail are
// de-prioritised by the caller).
//
// All public methods are safe for concurrent use. The learner never panics;
// validation errors are propagated through error returns.
package feedback

import (
	"time"
)

// --- FixOutcome --------------------------------------------------------------

// FixOutcome is the raw result of a single remediation attempt. It is the
// input to FeedbackLearner.Record. The fields capture enough context to
// reconstruct what was tried, against what, and whether it worked, so the
// learner can derive patterns without consulting external state.
type FixOutcome struct {
	// IncidentID is the identifier of the incident that triggered the
	// fix attempt. It may be empty when the fix was attempted directly
	// from an alert without an incident record.
	IncidentID string `json:"incident_id"`

	// AlertID is the identifier of the originating alert. It is kept on
	// the outcome so operators can trace a learning record back to the
	// alerting system.
	AlertID string `json:"alert_id"`

	// Target is the component that was remediated, e.g.
	// "order-service" or "node-3". It must be non-empty; the learner
	// rejects outcomes without a target.
	Target string `json:"target"`

	// Symptoms is the free-text symptom description observed at fix
	// time. It is tokenised by the learner when building patterns.
	Symptoms string `json:"symptoms"`

	// RootCause is the diagnosed root cause, e.g. "heap exhaustion".
	RootCause string `json:"root_cause"`

	// FixAction is the human-readable description of the action that
	// was taken, e.g. "restarted JVM with -Xmx4g". It must be
	// non-empty; the learner rejects outcomes without a fix action.
	FixAction string `json:"fix_action"`

	// Success is true when the fix resolved the alert without
	// rollback, false otherwise.
	Success bool `json:"success"`

	// Duration is the wall-clock time from fix start to fix
	// completion (or rollback). It is recorded so the learner can
	// surface slow fixes even when they succeed.
	Duration time.Duration `json:"duration"`

	// RollbackUsed is true when the fix was rolled back, which
	// implies Success is false.
	RollbackUsed bool `json:"rollback_used"`

	// Timestamp is the wall-clock time at which the outcome was
	// produced. It is used as the creation time of the derived
	// FeedbackRecord when non-zero; otherwise the learner stamps the
	// record with time.Now().UTC().
	Timestamp time.Time `json:"timestamp"`

	// Metrics is the optional bag of numeric metrics captured during
	// the fix (e.g. {"cpu_before": 0.95, "cpu_after": 0.31}). The
	// learner does not interpret the keys; it stores them verbatim so
	// downstream consumers can render trends.
	Metrics map[string]float64 `json:"metrics,omitempty"`

	// LessonsLearned is the optional list of free-text lessons
	// captured by the operator or the executor. They are stored on
	// the record and surfaced in stats for review.
	LessonsLearned []string `json:"lessons_learned,omitempty"`
}

// --- FeedbackRecord ----------------------------------------------------------

// FeedbackRecord is a persisted FixOutcome together with bookkeeping fields
// that link it to the pattern (if any) that suggested the fix. It is the unit
// of storage inside the learner.
type FeedbackRecord struct {
	// ID is the unique identifier of the record, a UUIDv4 generated by
	// the learner at creation time.
	ID string `json:"id"`

	// Outcome is the original fix outcome.
	Outcome FixOutcome `json:"outcome"`

	// PatternID is the identifier of the FixPattern that suggested
	// the fix, when applicable. It is empty when the fix was
	// operator-initiated or when no pattern matched.
	PatternID string `json:"pattern_id,omitempty"`

	// MatchScore is the score at which the pattern matched the
	// diagnosis, in the range [0, 1]. It is 0 when PatternID is
	// empty.
	MatchScore float64 `json:"match_score,omitempty"`

	// CreatedAt is the wall-clock time at which the record was
	// created.
	CreatedAt time.Time `json:"created_at"`
}

// --- LearningStats -----------------------------------------------------------

// LearningStats is the summary statistics returned by
// FeedbackLearner.GetStats. It is a point-in-time snapshot of the learner.
type LearningStats struct {
	// TotalRecords is the total number of records stored.
	TotalRecords int `json:"total_records"`

	// SuccessCount is the number of records with Outcome.Success ==
	// true.
	SuccessCount int `json:"success_count"`

	// FailureCount is the number of records with Outcome.Success ==
	// false.
	FailureCount int `json:"failure_count"`

	// SuccessRate is SuccessCount / TotalRecords, in the range
	// [0, 1]. It is 0 when TotalRecords is 0.
	SuccessRate float64 `json:"success_rate"`

	// TopPatterns is the per-pattern statistics sorted by descending
	// SuccessRate, then by descending Uses. It contains at most
	// maxTopPatterns entries.
	TopPatterns []PatternStat `json:"top_patterns"`

	// RecentRecords is the most recent records stored, ordered by
	// descending CreatedAt. It contains at most maxRecentRecords
	// entries.
	RecentRecords []FeedbackRecord `json:"recent_records"`
}

// --- PatternStat -------------------------------------------------------------

// PatternStat is the aggregated statistics for a single FixPattern across
// all feedback records that reference it.
type PatternStat struct {
	// PatternID is the identifier of the pattern. It matches
	// FixPattern.ID and FeedbackRecord.PatternID.
	PatternID string `json:"pattern_id"`

	// PatternDesc is the human-readable description of the pattern,
	// taken from FixPattern.Name at the time the pattern was first
	// seen. It may go stale if the pattern is later renamed.
	PatternDesc string `json:"pattern_desc"`

	// Uses is the total number of records that reference the pattern.
	Uses int `json:"uses"`

	// Successes is the number of records with Outcome.Success == true
	// that reference the pattern.
	Successes int `json:"successes"`

	// Failures is the number of records with Outcome.Success == false
	// that reference the pattern.
	Failures int `json:"failures"`

	// SuccessRate is Successes / Uses, in the range [0, 1]. It is 0
	// when Uses is 0.
	SuccessRate float64 `json:"success_rate"`
}
