run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocyclo
    - bodyclose
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/nexus/levee
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - ineffassign
        - unparam
  max-issues-per-linter: 0
  max-same-issues: 0