// silencer.go implements alert silencing. A SilenceRule matches alerts by
// their Labels (and optionally Source/Severity) and silences them for a
// bounded duration. The Silencer is concurrency-safe.
package alert

import (
	"fmt"
	"strings"
	"sync"
	"time"
)

// SilenceRule defines a single silencing rule. An alert is silenced when
// every key/value in Match is present in the alert's Labels with the same
// value, AND (if Source is non-empty) the alert Source matches, AND (if
// MinSeverity is non-zero) the alert severity is >= MinSeverity.
type SilenceRule struct {
	// ID is the rule identifier. Generated by AddRule when empty.
	ID string `json:"id"`
	// Match is the set of label key=value pairs that must all be present.
	Match map[string]string `json:"match"`
	// Source, when non-empty, restricts the rule to a single source.
	Source string `json:"source,omitempty"`
	// MinSeverity, when non-zero, restricts the rule to alerts with
	// severity >= MinSeverity.
	MinSeverity Severity `json:"min_severity,omitempty"`
	// Duration is how long the silence lasts from CreatedAt. Zero means
	// indefinite (until manually removed).
	Duration time.Duration `json:"duration"`
	// CreatedAt is when the rule was added.
	CreatedAt time.Time `json:"created_at"`
	// Expires is CreatedAt + Duration. Zero value means indefinite.
	Expires time.Time `json:"expires,omitempty"`
	// Reason is a human-readable explanation shown to operators.
	Reason string `json:"reason,omitempty"`
	// CreatedBy is the operator or process that created the rule.
	CreatedBy string `json:"created_by,omitempty"`
}

// Matches reports whether the rule matches the alert AND has not expired.
// A rule with no Match, no Source and zero MinSeverity matches every alert.
func (r *SilenceRule) Matches(a *Alert, now time.Time) bool {
	if r == nil || a == nil {
		return false
	}
	if !r.Expires.IsZero() && now.After(r.Expires) {
		return false
	}
	if r.Source != "" && r.Source != a.Source {
		return false
	}
	if r.MinSeverity != 0 && a.Severity < r.MinSeverity {
		return false
	}
	for k, v := range r.Match {
		if a.Labels[k] != v {
			return false
		}
	}
	return true
}

// Silencer holds the active silence rules. Construct with NewSilencer.
type Silencer struct {
	mu    sync.RWMutex
	rules map[string]*SilenceRule
	now   func() time.Time
	// idCounter is used to generate IDs when the caller does not supply one.
	idCounter uint64
}

// NewSilencer constructs an empty Silencer.
func NewSilencer() *Silencer {
	return &Silencer{
		rules: make(map[string]*SilenceRule),
		now:   time.Now,
	}
}

// AddRule registers a silence rule. If rule.ID is empty, a sequential ID of
// the form "silence-<n>" is generated. The rule's CreatedAt and Expires are
// populated when zero. The method returns the assigned ID.
func (s *Silencer) AddRule(rule SilenceRule) string {
	s.mu.Lock()
	defer s.mu.Unlock()

	if rule.ID == "" {
		s.idCounter++
		rule.ID = fmt.Sprintf("silence-%d", s.idCounter)
	}
	if rule.CreatedAt.IsZero() {
		rule.CreatedAt = s.now()
	}
	if rule.Duration > 0 && rule.Expires.IsZero() {
		rule.Expires = rule.CreatedAt.Add(rule.Duration)
	}
	s.rules[rule.ID] = &rule
	return rule.ID
}

// RemoveRule deletes the rule with the given ID. It returns true when the
// rule existed.
func (s *Silencer) RemoveRule(id string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, ok := s.rules[id]; !ok {
		return false
	}
	delete(s.rules, id)
	return true
}

// IsSilenced reports whether the alert matches any active (non-expired)
// silence rule. When true, the matching rule ID and reason are returned.
func (s *Silencer) IsSilenced(a *Alert) (bool, string, string) {
	if a == nil {
		return false, "", ""
	}
	now := s.now()
	s.mu.RLock()
	defer s.mu.RUnlock()
	// Iterate in sorted ID order so that the returned rule is deterministic
	// when several rules match.
	ids := make([]string, 0, len(s.rules))
	for id := range s.rules {
		ids = append(ids, id)
	}
	// Insertion sort: rule counts are typically small.
	for i := 1; i < len(ids); i++ {
		for j := i; j > 0 && ids[j-1] > ids[j]; j-- {
			ids[j-1], ids[j] = ids[j], ids[j-1]
		}
	}
	for _, id := range ids {
		r := s.rules[id]
		if r.Matches(a, now) {
			return true, r.ID, r.Reason
		}
	}
	return false, "", ""
}

// ListRules returns a snapshot of all rules sorted by ID. Expired rules are
// included; callers can filter on Expires if needed.
func (s *Silencer) ListRules() []SilenceRule {
	s.mu.RLock()
	defer s.mu.RUnlock()
	ids := make([]string, 0, len(s.rules))
	for id := range s.rules {
		ids = append(ids, id)
	}
	// Sort for stable output.
	for i := 1; i < len(ids); i++ {
		for j := i; j > 0 && ids[j-1] > ids[j]; j-- {
			ids[j-1], ids[j] = ids[j], ids[j-1]
		}
	}
	out := make([]SilenceRule, 0, len(ids))
	for _, id := range ids {
		out = append(out, *s.rules[id])
	}
	return out
}

// GetRule returns the rule with the given ID, or ErrAlertNotFound.
func (s *Silencer) GetRule(id string) (*SilenceRule, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	r, ok := s.rules[id]
	if !ok {
		return nil, fmt.Errorf("%w: silence rule %q", ErrAlertNotFound, id)
	}
	cp := *r
	return &cp, nil
}

// Cleanup removes expired rules. It returns the number of rules removed.
func (s *Silencer) Cleanup() int {
	now := s.now()
	s.mu.Lock()
	defer s.mu.Unlock()
	var removed int
	for id, r := range s.rules {
		if !r.Expires.IsZero() && now.After(r.Expires) {
			delete(s.rules, id)
			removed++
		}
	}
	return removed
}

// Size returns the number of rules currently registered.
func (s *Silencer) Size() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.rules)
}

// matchLabels is a small helper used by tests; it builds a label map from
// "k1=v1,k2=v2" form. Empty segments are ignored.
func matchLabels(s string) map[string]string {
	if s == "" {
		return nil
	}
	out := make(map[string]string)
	for _, pair := range strings.Split(s, ",") {
		k, v, ok := strings.Cut(pair, "=")
		if !ok {
			continue
		}
		out[strings.TrimSpace(k)] = strings.TrimSpace(v)
	}
	return out
}
