-- LEVEE PostgreSQL schema: state, audit, lock and credential storage.
-- All tables use TEXT primary keys (hex IDs generated by the application).
-- Timestamps are stored as TIMESTAMPTZ (timezone-aware UTC).
-- JSON columns (params, detail) are stored as TEXT and validated by the application.
--
-- This schema mirrors internal/state/schema.sql (SQLite) but uses PostgreSQL
-- syntax: BIGINT for row counts, TIMESTAMPTZ for timestamps, BYTEA for blobs,
-- and PostgreSQL trigger functions for WORM protection.

-- Schema version tracking for migrations.
CREATE TABLE IF NOT EXISTS schema_version (
    version    INTEGER PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- runs: change run records (top-level execution unit).
CREATE TABLE IF NOT EXISTS runs (
    id              TEXT    PRIMARY KEY,
    workflow_name   TEXT    NOT NULL,
    template_name   TEXT    NOT NULL,
    params          TEXT    NOT NULL DEFAULT '{}',  -- JSON encoded parameters
    plan_hash       TEXT    NOT NULL,
    status          TEXT    NOT NULL,                -- pending|planning|awaiting_approval|running|verifying|completed|failed|rolled_back|aborted
    approval_status TEXT    NOT NULL DEFAULT 'pending', -- pending|approved|rejected (see state.ApprovalStatus*; NOT the approvals table's set)
    approval_level  TEXT    NOT NULL DEFAULT '',     -- low|medium|high|critical
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    creator         TEXT    NOT NULL,
    incident_id     TEXT    NOT NULL DEFAULT '',
    plan_json       TEXT    NOT NULL DEFAULT ''      -- canonical plan.Plan JSON ('' = not planned; v3, last: mirrors ALTER append order)
    -- Multi-tenancy (v6). Mirrors the SQLite schema: denormalised onto every
    -- tenant-owned table so each read is a plain indexed predicate. NOT NULL
    -- DEFAULT '' so the pre-multi-tenant rows stay readable as "unowned".
    , tenant_id     TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_runs_status       ON runs (status);
CREATE INDEX IF NOT EXISTS idx_runs_workflow     ON runs (workflow_name);
CREATE INDEX IF NOT EXISTS idx_runs_template     ON runs (template_name);
CREATE INDEX IF NOT EXISTS idx_runs_creator      ON runs (creator);
CREATE INDEX IF NOT EXISTS idx_runs_incident     ON runs (incident_id);
CREATE INDEX IF NOT EXISTS idx_runs_created_at   ON runs (created_at);
CREATE INDEX IF NOT EXISTS idx_runs_tenant       ON runs (tenant_id);

-- batches: batch records (one run has N batches executed serially).
CREATE TABLE IF NOT EXISTS batches (
    id            TEXT    PRIMARY KEY,
    run_id        TEXT    NOT NULL,
    batch_no      INTEGER NOT NULL,
    status        TEXT    NOT NULL,                  -- pending|running|completed|done|failed|rolled_back|interrupted
    total_hosts   INTEGER NOT NULL DEFAULT 0,
    succeeded     INTEGER NOT NULL DEFAULT 0,
    failed        INTEGER NOT NULL DEFAULT 0,
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    tenant_id     TEXT    NOT NULL DEFAULT '',      -- v6: mirrors runs.tenant_id
    FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE CASCADE,
    UNIQUE (run_id, batch_no)
);

CREATE INDEX IF NOT EXISTS idx_batches_run_id   ON batches (run_id);
CREATE INDEX IF NOT EXISTS idx_batches_status   ON batches (status);
CREATE INDEX IF NOT EXISTS idx_batches_tenant   ON batches (tenant_id);

-- steps: per-host step execution records.
CREATE TABLE IF NOT EXISTS steps (
    id            TEXT    PRIMARY KEY,
    run_id        TEXT    NOT NULL,
    batch_id      TEXT    NOT NULL,
    host          TEXT    NOT NULL,
    step_name     TEXT    NOT NULL,
    action        TEXT    NOT NULL,
    status        TEXT    NOT NULL,                  -- pending|running|success|failed|skipped
    exit_code     INTEGER,
    stdout        TEXT    NOT NULL DEFAULT '',
    stderr        TEXT    NOT NULL DEFAULT '',
    duration_ms   INTEGER NOT NULL DEFAULT 0,
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    tenant_id     TEXT    NOT NULL DEFAULT '',      -- v6: mirrors runs.tenant_id
    FOREIGN KEY (run_id)   REFERENCES runs    (id) ON DELETE CASCADE,
    FOREIGN KEY (batch_id) REFERENCES batches (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_steps_run_id    ON steps (run_id);
CREATE INDEX IF NOT EXISTS idx_steps_batch_id  ON steps (batch_id);
CREATE INDEX IF NOT EXISTS idx_steps_host      ON steps (host);
CREATE INDEX IF NOT EXISTS idx_steps_status    ON steps (status);
CREATE INDEX IF NOT EXISTS idx_steps_tenant    ON steps (tenant_id);

-- trace: audit trace records forming a hash chain per run.
CREATE TABLE IF NOT EXISTS trace (
    id         TEXT    PRIMARY KEY,
    run_id     TEXT    NOT NULL,
    event      TEXT    NOT NULL,                     -- plan|batch_start|step_start|step_end|batch_end|verify|rollback|approval|archive
    actor      TEXT    NOT NULL,
    detail     TEXT    NOT NULL DEFAULT '{}',        -- JSON encoded detail
    prev_hash  TEXT    NOT NULL DEFAULT '',
    curr_hash  TEXT    NOT NULL,
    timestamp  TIMESTAMPTZ NOT NULL,
    -- tenant_id is declared LAST on purpose: the v6 step adds it with ALTER
    -- TABLE ... ADD COLUMN, which always appends, so a fresh database and an
    -- upgraded one only agree on column order if the column sits at the end.
    tenant_id  TEXT    NOT NULL DEFAULT '',           -- v6: mirrors runs.tenant_id; WORM-protected below
    FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_trace_run_id    ON trace (run_id);
CREATE INDEX IF NOT EXISTS idx_trace_event     ON trace (event);
CREATE INDEX IF NOT EXISTS idx_trace_timestamp ON trace (timestamp);
CREATE INDEX IF NOT EXISTS idx_trace_tenant    ON trace (tenant_id);

-- WORM protection: prevent UPDATE on trace content fields. The trigger only
-- fires when one of the immutable content columns (id, run_id, event, actor,
-- detail, timestamp) is changed. Updating prev_hash and curr_hash is allowed
-- because the hash-chain builder (HashChainBuilder.Build) needs to write these
-- values after the record has been inserted.
--
-- tenant_id is in this list on purpose: without it an UPDATE could move a
-- trace row into another tenant's scope (or out of one), which is exactly the
-- tamper the chain exists to make detectable. It is immutable from insert.
CREATE OR REPLACE FUNCTION levee_worm_prevent_trace_update() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.run_id IS DISTINCT FROM OLD.run_id
       OR NEW.event IS DISTINCT FROM OLD.event
       OR NEW.actor IS DISTINCT FROM OLD.actor
       OR NEW.detail IS DISTINCT FROM OLD.detail
       OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
       OR NEW.timestamp IS DISTINCT FROM OLD.timestamp THEN
        RAISE EXCEPTION 'WORM violation: trace content fields cannot be updated';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS worm_prevent_trace_update ON trace;
CREATE TRIGGER worm_prevent_trace_update
    BEFORE UPDATE ON trace
    FOR EACH ROW
    EXECUTE FUNCTION levee_worm_prevent_trace_update();

-- WORM protection: prevent DELETE on trace table. Audit trace records are
-- append-only and must never be removed.
CREATE OR REPLACE FUNCTION levee_worm_prevent_trace_delete() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'WORM violation: trace records cannot be deleted';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS worm_prevent_trace_delete ON trace;
CREATE TRIGGER worm_prevent_trace_delete
    BEFORE DELETE ON trace
    FOR EACH ROW
    EXECUTE FUNCTION levee_worm_prevent_trace_delete();

-- approvals: approval records (multi-level approval chain).
CREATE TABLE IF NOT EXISTS approvals (
    id         TEXT    PRIMARY KEY,
    run_id     TEXT    NOT NULL,
    level      TEXT    NOT NULL,                     -- low|medium|high|critical
    approver   TEXT    NOT NULL,
    status     TEXT    NOT NULL,                     -- pending|approved|rejected|timeout
    comment    TEXT    NOT NULL DEFAULT '',
    timeout_at TIMESTAMPTZ,
    acted_at   TIMESTAMPTZ,
    plan_hash  TEXT    NOT NULL DEFAULT '',          -- D-1 v2: plan the approval attests to ('' = legacy, any plan)
    revision   BIGINT  NOT NULL DEFAULT 0,           -- D-1 v2: optimistic-lock version for concurrent decisions
    tenant_id  TEXT    NOT NULL DEFAULT '',           -- v6: mirrors runs.tenant_id
    FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_approvals_run_id    ON approvals (run_id);
CREATE INDEX IF NOT EXISTS idx_approvals_status    ON approvals (status);
CREATE INDEX IF NOT EXISTS idx_approvals_approver  ON approvals (approver);
CREATE INDEX IF NOT EXISTS idx_approvals_tenant    ON approvals (tenant_id);

-- locks: mutex locks with TTL (target-host level).
--
-- DELIBERATELY NOT TENANT-SCOPED (v6) — see the identical note in schema.sql.
-- A lock guards one physical host; scoping it per tenant would let two
-- tenants hold the same host and both be admitted, which is the exact
-- concurrent-change collision the lock exists to prevent.
CREATE TABLE IF NOT EXISTS locks (
    id           TEXT    PRIMARY KEY,
    scope        TEXT    NOT NULL,                   -- e.g. host:<hostname> or run:<run_id>
    owner        TEXT    NOT NULL,                   -- run_id or process identifier
    ttl_seconds  INTEGER NOT NULL,
    acquired_at  TIMESTAMPTZ NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    UNIQUE (scope)
);

CREATE INDEX IF NOT EXISTS idx_locks_scope      ON locks (scope);
CREATE INDEX IF NOT EXISTS idx_locks_owner      ON locks (owner);
CREATE INDEX IF NOT EXISTS idx_locks_expires_at ON locks (expires_at);

-- credentials: encrypted credential references (MVP local encryption).
CREATE TABLE IF NOT EXISTS credentials (
    id             TEXT    PRIMARY KEY,
    name           TEXT    NOT NULL,
    type           TEXT    NOT NULL,                 -- ssh_key|ssh_password|winrm|vault_ref|token
    encrypted_data BYTEA   NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,
    rotated_at     TIMESTAMPTZ,
    tags           TEXT    NOT NULL DEFAULT '',      -- v2: JSON map[string]string, '' = none
    tenant_id      TEXT    NOT NULL DEFAULT '',      -- v6: owning tenant (secrets must not cross tenants)
    UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS idx_credentials_name ON credentials (name);
CREATE INDEX IF NOT EXISTS idx_credentials_type ON credentials (type);
CREATE INDEX IF NOT EXISTS idx_credentials_tenant ON credentials (tenant_id);

-- audit: audit log entries (separate from trace; high-level actions).
CREATE TABLE IF NOT EXISTS audit (
    id         TEXT    PRIMARY KEY,
    run_id     TEXT    NOT NULL DEFAULT '',
    action     TEXT    NOT NULL,                     -- plan|apply|verify|rollback|approval|lock|credential|archive|login|config
    actor      TEXT    NOT NULL,
    target     TEXT    NOT NULL DEFAULT '',
    result     TEXT    NOT NULL,                     -- success|failure|denied|error
    timestamp  TIMESTAMPTZ NOT NULL,
    tenant_id  TEXT    NOT NULL DEFAULT '',          -- v6: owning tenant (NOT derivable — run_id may be ''); declared last, see the note on trace.tenant_id
    -- v7: the chain. GLOBAL, not per-run like trace: an audit row with an
    -- empty run_id is exactly the security-relevant kind (login, config,
    -- credential), and a per-run chain cannot cover it. Ordering for both
    -- build and verify is (timestamp, id) so the chain is reproducible.
    prev_hash  TEXT    NOT NULL DEFAULT '',
    curr_hash  TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_audit_run_id    ON audit (run_id);
CREATE INDEX IF NOT EXISTS idx_audit_action    ON audit (action);
CREATE INDEX IF NOT EXISTS idx_audit_actor     ON audit (actor);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit (timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_tenant    ON audit (tenant_id);
-- The chain is verified by walking (timestamp, id) in order; this index makes
-- that walk an index scan instead of a sort.
CREATE INDEX IF NOT EXISTS idx_audit_chain     ON audit (timestamp, id);

-- WORM protection for audit. The hash chain alone detects edits but not the
-- deletion of a tampered row, so the database has to refuse both. As on trace,
-- prev_hash/curr_hash stay updatable because the chain builder writes them
-- after insert; every content column is immutable.
CREATE OR REPLACE FUNCTION levee_worm_prevent_audit_update() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.run_id IS DISTINCT FROM OLD.run_id
       OR NEW.action IS DISTINCT FROM OLD.action
       OR NEW.actor IS DISTINCT FROM OLD.actor
       OR NEW.target IS DISTINCT FROM OLD.target
       OR NEW.result IS DISTINCT FROM OLD.result
       OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
       OR NEW.timestamp IS DISTINCT FROM OLD.timestamp THEN
        RAISE EXCEPTION 'WORM violation: audit content fields cannot be updated';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS worm_prevent_audit_update ON audit;
CREATE TRIGGER worm_prevent_audit_update
    BEFORE UPDATE ON audit
    FOR EACH ROW
    EXECUTE FUNCTION levee_worm_prevent_audit_update();

CREATE OR REPLACE FUNCTION levee_worm_prevent_audit_delete() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'WORM violation: audit records cannot be deleted';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS worm_prevent_audit_delete ON audit;
CREATE TRIGGER worm_prevent_audit_delete
    BEFORE DELETE ON audit
    FOR EACH ROW
    EXECUTE FUNCTION levee_worm_prevent_audit_delete();

-- cluster_nodes: registered cluster members (master + workers) is NOT defined
-- here. It lives in internal/dbschema.ClusterNodesDDL because the cluster
-- package creates it too; this file's content is concatenated with that one
-- definition at apply time (see pgSchemaFull in pgstore.go).
-- Only used in cluster mode (PostgreSQL backend).

-- ---------------------------------------------------------------------------
-- Inventory: managed target hosts and hierarchical groups (v1.11)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_groups (
    id         TEXT        PRIMARY KEY,
    name       TEXT        NOT NULL UNIQUE,
    parent_id  TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tenant_id  TEXT        NOT NULL DEFAULT ''     -- v6: owning tenant
);

CREATE INDEX IF NOT EXISTS idx_inventory_groups_tenant ON inventory_groups (tenant_id);

CREATE TABLE IF NOT EXISTS targets (
    id              TEXT        PRIMARY KEY,
    hostname        TEXT        NOT NULL,
    port            INTEGER     NOT NULL DEFAULT 22,
    channel_type    TEXT        NOT NULL DEFAULT 'ssh',
    credential_ref  TEXT        NOT NULL DEFAULT '',
    labels          JSONB       NOT NULL DEFAULT '{}',
    group_id        TEXT,
    status          TEXT        NOT NULL DEFAULT 'active',
    reachable       BOOLEAN     NOT NULL DEFAULT FALSE,
    last_checked_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tenant_id       TEXT        NOT NULL DEFAULT '',  -- v6: owning tenant
    -- UNIQUE stays table-wide: a host is one physical machine regardless of
    -- which tenant is allowed to change it.
    UNIQUE (hostname, port),
    FOREIGN KEY (group_id) REFERENCES inventory_groups (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_targets_group  ON targets (group_id);
CREATE INDEX IF NOT EXISTS idx_targets_status ON targets (status);
CREATE INDEX IF NOT EXISTS idx_targets_tenant ON targets (tenant_id);

-- ---------------------------------------------------------------------------
-- run_assignment: cross-node dispatch assignments (design-cluster-dispatch.md).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS run_assignment (
    run_id      TEXT PRIMARY KEY,
    owner_node  TEXT NOT NULL,
    epoch       BIGINT NOT NULL,
    state       TEXT NOT NULL,
    result      TEXT NOT NULL DEFAULT '',
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tenant_id   TEXT        NOT NULL DEFAULT '',   -- v6: mirrors runs.tenant_id
    UNIQUE (run_id, epoch)
);

CREATE INDEX IF NOT EXISTS idx_assignment_owner_state ON run_assignment (owner_node, state);
CREATE INDEX IF NOT EXISTS idx_assignment_state ON run_assignment (state);
CREATE INDEX IF NOT EXISTS idx_assignment_tenant ON run_assignment (tenant_id);

-- ---------------------------------------------------------------------------
-- Agent registry (v8): the LEVEE agents that have registered with the master.
-- Mirrors the identical block in schema.sql; only the types differ
-- (TIMESTAMPTZ for timestamps). See that file for why the table is not
-- tenant-scoped, why capabilities is a JSON array in TEXT rather than a
-- delimiter-joined list ('[]' = none), and why last_heartbeat is nullable
-- (NULL = no heartbeat has ever arrived).
CREATE TABLE IF NOT EXISTS agents (
    id                TEXT        PRIMARY KEY,
    address           TEXT        NOT NULL,               -- host:port the agent listens on
    capabilities      TEXT        NOT NULL DEFAULT '[]',  -- JSON encoded []string, '[]' = none
    status            TEXT        NOT NULL DEFAULT 'idle',
    last_heartbeat    TIMESTAMPTZ,                        -- NULL = never heartbeated
    registered_at     TIMESTAMPTZ NOT NULL,
    active_tasks      INTEGER     NOT NULL DEFAULT 0,
    completed_tasks   BIGINT      NOT NULL DEFAULT 0,
    failed_tasks      BIGINT      NOT NULL DEFAULT 0,
    max_concurrent    INTEGER     NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_agents_status ON agents (status);