-- LEVEE PostgreSQL schema: state, audit, lock and credential storage.
-- All tables use TEXT primary keys (hex IDs generated by the application).
-- Timestamps are stored as TIMESTAMPTZ (timezone-aware UTC).
-- JSON columns (params, detail) are stored as TEXT and validated by the application.
--
-- This schema mirrors internal/state/schema.sql (SQLite) but uses PostgreSQL
-- syntax: BIGINT for row counts, TIMESTAMPTZ for timestamps, BYTEA for blobs,
-- and PostgreSQL trigger functions for WORM protection.

-- Schema version tracking for migrations.
CREATE TABLE IF NOT EXISTS schema_version (
    version    INTEGER PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- runs: change run records (top-level execution unit).
CREATE TABLE IF NOT EXISTS runs (
    id              TEXT    PRIMARY KEY,
    workflow_name   TEXT    NOT NULL,
    template_name   TEXT    NOT NULL,
    params          TEXT    NOT NULL DEFAULT '{}',  -- JSON encoded parameters
    plan_hash       TEXT    NOT NULL,
    status          TEXT    NOT NULL,                -- pending|planning|awaiting_approval|running|verifying|completed|failed|rolled_back|aborted
    approval_status TEXT    NOT NULL DEFAULT 'pending', -- pending|approved|rejected|timeout|skipped
    approval_level  TEXT    NOT NULL DEFAULT '',     -- low|medium|high|critical
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    creator         TEXT    NOT NULL,
    incident_id     TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_runs_status       ON runs (status);
CREATE INDEX IF NOT EXISTS idx_runs_workflow     ON runs (workflow_name);
CREATE INDEX IF NOT EXISTS idx_runs_template     ON runs (template_name);
CREATE INDEX IF NOT EXISTS idx_runs_creator      ON runs (creator);
CREATE INDEX IF NOT EXISTS idx_runs_incident     ON runs (incident_id);
CREATE INDEX IF NOT EXISTS idx_runs_created_at   ON runs (created_at);

-- batches: batch records (one run has N batches executed serially).
CREATE TABLE IF NOT EXISTS batches (
    id            TEXT    PRIMARY KEY,
    run_id        TEXT    NOT NULL,
    batch_no      INTEGER NOT NULL,
    status        TEXT    NOT NULL,                  -- pending|running|completed|failed|skipped
    total_hosts   INTEGER NOT NULL DEFAULT 0,
    succeeded     INTEGER NOT NULL DEFAULT 0,
    failed        INTEGER NOT NULL DEFAULT 0,
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE CASCADE,
    UNIQUE (run_id, batch_no)
);

CREATE INDEX IF NOT EXISTS idx_batches_run_id   ON batches (run_id);
CREATE INDEX IF NOT EXISTS idx_batches_status   ON batches (status);

-- steps: per-host step execution records.
CREATE TABLE IF NOT EXISTS steps (
    id            TEXT    PRIMARY KEY,
    run_id        TEXT    NOT NULL,
    batch_id      TEXT    NOT NULL,
    host          TEXT    NOT NULL,
    step_name     TEXT    NOT NULL,
    action        TEXT    NOT NULL,
    status        TEXT    NOT NULL,                  -- pending|running|success|failed|skipped
    exit_code     INTEGER,
    stdout        TEXT    NOT NULL DEFAULT '',
    stderr        TEXT    NOT NULL DEFAULT '',
    duration_ms   INTEGER NOT NULL DEFAULT 0,
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    FOREIGN KEY (run_id)   REFERENCES runs    (id) ON DELETE CASCADE,
    FOREIGN KEY (batch_id) REFERENCES batches (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_steps_run_id    ON steps (run_id);
CREATE INDEX IF NOT EXISTS idx_steps_batch_id  ON steps (batch_id);
CREATE INDEX IF NOT EXISTS idx_steps_host      ON steps (host);
CREATE INDEX IF NOT EXISTS idx_steps_status    ON steps (status);

-- trace: audit trace records forming a hash chain per run.
CREATE TABLE IF NOT EXISTS trace (
    id         TEXT    PRIMARY KEY,
    run_id     TEXT    NOT NULL,
    event      TEXT    NOT NULL,                     -- plan|batch_start|step_start|step_end|batch_end|verify|rollback|approval|archive
    actor      TEXT    NOT NULL,
    detail     TEXT    NOT NULL DEFAULT '{}',        -- JSON encoded detail
    prev_hash  TEXT    NOT NULL DEFAULT '',
    curr_hash  TEXT    NOT NULL,
    timestamp  TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_trace_run_id    ON trace (run_id);
CREATE INDEX IF NOT EXISTS idx_trace_event     ON trace (event);
CREATE INDEX IF NOT EXISTS idx_trace_timestamp ON trace (timestamp);

-- WORM protection: prevent UPDATE on trace content fields. The trigger only
-- fires when one of the immutable content columns (id, run_id, event, actor,
-- detail, timestamp) is changed. Updating prev_hash and curr_hash is allowed
-- because the hash-chain builder (HashChainBuilder.Build) needs to write these
-- values after the record has been inserted.
CREATE OR REPLACE FUNCTION levee_worm_prevent_trace_update() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.run_id IS DISTINCT FROM OLD.run_id
       OR NEW.event IS DISTINCT FROM OLD.event
       OR NEW.actor IS DISTINCT FROM OLD.actor
       OR NEW.detail IS DISTINCT FROM OLD.detail
       OR NEW.timestamp IS DISTINCT FROM OLD.timestamp THEN
        RAISE EXCEPTION 'WORM violation: trace content fields cannot be updated';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS worm_prevent_trace_update ON trace;
CREATE TRIGGER worm_prevent_trace_update
    BEFORE UPDATE ON trace
    FOR EACH ROW
    EXECUTE FUNCTION levee_worm_prevent_trace_update();

-- WORM protection: prevent DELETE on trace table. Audit trace records are
-- append-only and must never be removed.
CREATE OR REPLACE FUNCTION levee_worm_prevent_trace_delete() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'WORM violation: trace records cannot be deleted';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS worm_prevent_trace_delete ON trace;
CREATE TRIGGER worm_prevent_trace_delete
    BEFORE DELETE ON trace
    FOR EACH ROW
    EXECUTE FUNCTION levee_worm_prevent_trace_delete();

-- approvals: approval records (multi-level approval chain).
CREATE TABLE IF NOT EXISTS approvals (
    id         TEXT    PRIMARY KEY,
    run_id     TEXT    NOT NULL,
    level      TEXT    NOT NULL,                     -- low|medium|high|critical
    approver   TEXT    NOT NULL,
    status     TEXT    NOT NULL,                     -- pending|approved|rejected|timeout
    comment    TEXT    NOT NULL DEFAULT '',
    timeout_at TIMESTAMPTZ,
    acted_at   TIMESTAMPTZ,
    FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_approvals_run_id    ON approvals (run_id);
CREATE INDEX IF NOT EXISTS idx_approvals_status    ON approvals (status);
CREATE INDEX IF NOT EXISTS idx_approvals_approver  ON approvals (approver);

-- locks: mutex locks with TTL (target-host level).
CREATE TABLE IF NOT EXISTS locks (
    id           TEXT    PRIMARY KEY,
    scope        TEXT    NOT NULL,                   -- e.g. host:<hostname> or run:<run_id>
    owner        TEXT    NOT NULL,                   -- run_id or process identifier
    ttl_seconds  INTEGER NOT NULL,
    acquired_at  TIMESTAMPTZ NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    UNIQUE (scope)
);

CREATE INDEX IF NOT EXISTS idx_locks_scope      ON locks (scope);
CREATE INDEX IF NOT EXISTS idx_locks_owner      ON locks (owner);
CREATE INDEX IF NOT EXISTS idx_locks_expires_at ON locks (expires_at);

-- credentials: encrypted credential references (MVP local encryption).
CREATE TABLE IF NOT EXISTS credentials (
    id             TEXT    PRIMARY KEY,
    name           TEXT    NOT NULL,
    type           TEXT    NOT NULL,                 -- ssh_key|ssh_password|winrm|vault_ref|token
    encrypted_data BYTEA   NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,
    rotated_at     TIMESTAMPTZ,
    UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS idx_credentials_name ON credentials (name);
CREATE INDEX IF NOT EXISTS idx_credentials_type ON credentials (type);

-- audit: audit log entries (separate from trace; high-level actions).
CREATE TABLE IF NOT EXISTS audit (
    id         TEXT    PRIMARY KEY,
    run_id     TEXT    NOT NULL DEFAULT '',
    action     TEXT    NOT NULL,                     -- plan|apply|verify|rollback|approval|lock|credential|archive|login|config
    actor      TEXT    NOT NULL,
    target     TEXT    NOT NULL DEFAULT '',
    result     TEXT    NOT NULL,                     -- success|failure|denied|error
    timestamp  TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_run_id    ON audit (run_id);
CREATE INDEX IF NOT EXISTS idx_audit_action    ON audit (action);
CREATE INDEX IF NOT EXISTS idx_audit_actor     ON audit (actor);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit (timestamp);

-- cluster_nodes: registered cluster members (master + workers).
-- Only used in cluster mode (PostgreSQL backend).
CREATE TABLE IF NOT EXISTS cluster_nodes (
    id              TEXT    PRIMARY KEY,
    address         TEXT    NOT NULL,
    status          TEXT    NOT NULL,                -- active|leaving|offline
    role            TEXT    NOT NULL,                -- master|worker
    last_heartbeat  TIMESTAMPTZ NOT NULL,
    capabilities    TEXT    NOT NULL DEFAULT '{}',   -- JSON encoded
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (address)
);

CREATE INDEX IF NOT EXISTS idx_cluster_nodes_status ON cluster_nodes (status);
CREATE INDEX IF NOT EXISTS idx_cluster_nodes_role   ON cluster_nodes (role);

-- ---------------------------------------------------------------------------
-- Inventory: managed target hosts and hierarchical groups (v1.11)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_groups (
    id         TEXT        PRIMARY KEY,
    name       TEXT        NOT NULL UNIQUE,
    parent_id  TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS targets (
    id              TEXT        PRIMARY KEY,
    hostname        TEXT        NOT NULL,
    port            INTEGER     NOT NULL DEFAULT 22,
    channel_type    TEXT        NOT NULL DEFAULT 'ssh',
    credential_ref  TEXT        NOT NULL DEFAULT '',
    labels          JSONB       NOT NULL DEFAULT '{}',
    group_id        TEXT,
    status          TEXT        NOT NULL DEFAULT 'active',
    reachable       BOOLEAN     NOT NULL DEFAULT FALSE,
    last_checked_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (hostname, port),
    FOREIGN KEY (group_id) REFERENCES inventory_groups (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_targets_group  ON targets (group_id);
CREATE INDEX IF NOT EXISTS idx_targets_status ON targets (status);