-- LEVEE SQLite schema: state, audit, lock and credential storage.
-- All tables use TEXT primary keys (UUIDs generated by the application).
-- Timestamps are stored as DATETIME (SQLite TEXT in ISO8601).
-- JSON columns (params, detail) are stored as TEXT and validated by the application.

-- Schema version tracking for migrations.
CREATE TABLE IF NOT EXISTS schema_version (
    version    INTEGER PRIMARY KEY,
    applied_at DATETIME NOT NULL DEFAULT (datetime('now'))
);

-- runs: change run records (top-level execution unit).
CREATE TABLE IF NOT EXISTS runs (
    id              TEXT    PRIMARY KEY,
    workflow_name   TEXT    NOT NULL,
    template_name   TEXT    NOT NULL,
    params          TEXT    NOT NULL DEFAULT '{}',  -- JSON encoded parameters
    plan_hash       TEXT    NOT NULL,
    status          TEXT    NOT NULL,                -- pending|planning|awaiting_approval|running|verifying|completed|failed|rolled_back|aborted
    approval_status TEXT    NOT NULL DEFAULT 'pending', -- pending|approved|rejected (see state.ApprovalStatus*; NOT the approvals table's set)
    approval_level  TEXT    NOT NULL DEFAULT '',     -- low|medium|high|critical
    created_at      DATETIME NOT NULL,
    updated_at      DATETIME NOT NULL,
    creator         TEXT    NOT NULL,
    incident_id     TEXT    NOT NULL DEFAULT '',
    -- SPLITTER HAZARD (see store_edge_test.go "sqlite schema" tests): the
    -- SQLite splitter ends a statement when a LINE ends with ';'. A column
    -- line with a trailing inline comment may contain ';' inside the
    -- comment, but must never END with ';' — keep the closing ');' on its
    -- own line. The PG splitter learned this the hard way (inline
    -- comment with ';' cut a CREATE TABLE in half, SQLSTATE 42601).
    plan_json       TEXT    NOT NULL DEFAULT '',     -- canonical plan.Plan JSON ('' = not planned; v3, last: mirrors ALTER append order)
    -- Multi-tenancy (v6). Denormalised onto every tenant-owned table so each
    -- read is a plain indexed predicate; see Run.TenantID in store.go. NOT NULL
    -- DEFAULT '' keeps the pre-multi-tenant rows readable as "unowned", which
    -- is what the v6 migration leaves behind for tables with no run parent.
    tenant_id       TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_runs_status       ON runs (status);
CREATE INDEX IF NOT EXISTS idx_runs_workflow     ON runs (workflow_name);
CREATE INDEX IF NOT EXISTS idx_runs_template     ON runs (template_name);
CREATE INDEX IF NOT EXISTS idx_runs_creator      ON runs (creator);
CREATE INDEX IF NOT EXISTS idx_runs_incident     ON runs (incident_id);
CREATE INDEX IF NOT EXISTS idx_runs_created_at   ON runs (created_at);
CREATE INDEX IF NOT EXISTS idx_runs_tenant       ON runs (tenant_id);

-- batches: batch records (one run has N batches executed serially).
CREATE TABLE IF NOT EXISTS batches (
    id            TEXT    PRIMARY KEY,
    run_id        TEXT    NOT NULL,
    batch_no      INTEGER NOT NULL,
    status        TEXT    NOT NULL,                  -- pending|running|completed|done|failed|rolled_back|interrupted
    total_hosts   INTEGER NOT NULL DEFAULT 0,
    succeeded     INTEGER NOT NULL DEFAULT 0,
    failed        INTEGER NOT NULL DEFAULT 0,
    started_at    DATETIME,
    completed_at  DATETIME,
    tenant_id     TEXT    NOT NULL DEFAULT '',     -- v6: mirrors runs.tenant_id
    FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE CASCADE,
    UNIQUE (run_id, batch_no)
);

CREATE INDEX IF NOT EXISTS idx_batches_run_id   ON batches (run_id);
CREATE INDEX IF NOT EXISTS idx_batches_status   ON batches (status);
CREATE INDEX IF NOT EXISTS idx_batches_tenant   ON batches (tenant_id);

-- steps: per-host step execution records.
CREATE TABLE IF NOT EXISTS steps (
    id            TEXT    PRIMARY KEY,
    run_id        TEXT    NOT NULL,
    batch_id      TEXT    NOT NULL,
    host          TEXT    NOT NULL,
    step_name     TEXT    NOT NULL,
    action        TEXT    NOT NULL,
    status        TEXT    NOT NULL,                  -- pending|running|success|failed|skipped
    exit_code     INTEGER,
    stdout        TEXT    NOT NULL DEFAULT '',
    stderr        TEXT    NOT NULL DEFAULT '',
    duration_ms   INTEGER NOT NULL DEFAULT 0,
    started_at    DATETIME,
    completed_at  DATETIME,
    tenant_id     TEXT    NOT NULL DEFAULT '',      -- v6: mirrors runs.tenant_id
    FOREIGN KEY (run_id)   REFERENCES runs    (id) ON DELETE CASCADE,
    FOREIGN KEY (batch_id) REFERENCES batches (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_steps_run_id    ON steps (run_id);
CREATE INDEX IF NOT EXISTS idx_steps_batch_id  ON steps (batch_id);
CREATE INDEX IF NOT EXISTS idx_steps_host      ON steps (host);
CREATE INDEX IF NOT EXISTS idx_steps_status    ON steps (status);
CREATE INDEX IF NOT EXISTS idx_steps_tenant    ON steps (tenant_id);

-- trace: audit trace records forming a hash chain per run.
CREATE TABLE IF NOT EXISTS trace (
    id         TEXT    PRIMARY KEY,
    run_id     TEXT    NOT NULL,
    event      TEXT    NOT NULL,                     -- plan|batch_start|step_start|step_end|batch_end|verify|rollback|approval|archive
    actor      TEXT    NOT NULL,
    detail     TEXT    NOT NULL DEFAULT '{}',        -- JSON encoded detail
    prev_hash  TEXT    NOT NULL DEFAULT '',
    curr_hash  TEXT    NOT NULL,
    timestamp  DATETIME NOT NULL,
    -- tenant_id is declared LAST on purpose: the v6 step adds it with ALTER
    -- TABLE ... ADD COLUMN, which always appends, so a fresh database and an
    -- upgraded one only agree on column order if the column sits at the end.
    -- TestMigrate_FreshAndUpgraded_SchemaShapesMatch enforces this.
    tenant_id  TEXT    NOT NULL DEFAULT '',           -- v6: mirrors runs.tenant_id; WORM-protected below
    FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_trace_run_id    ON trace (run_id);
CREATE INDEX IF NOT EXISTS idx_trace_event     ON trace (event);
CREATE INDEX IF NOT EXISTS idx_trace_timestamp ON trace (timestamp);
CREATE INDEX IF NOT EXISTS idx_trace_tenant    ON trace (tenant_id);

-- WORM protection: prevent UPDATE on trace content fields. The trigger only
-- fires when one of the immutable content columns (id, run_id, event, actor,
-- detail, timestamp) is changed. Updating prev_hash and curr_hash is allowed
-- because the hash-chain builder (HashChainBuilder.Build) needs to write these
-- values after the record has been inserted.
--
-- tenant_id is in this list on purpose: without it an UPDATE could move a
-- trace row into another tenant's scope (or out of one), which is exactly the
-- tamper the chain exists to make detectable. It is immutable from insert.
CREATE TRIGGER IF NOT EXISTS worm_prevent_trace_update
BEFORE UPDATE ON trace
WHEN NEW.id != OLD.id
  OR NEW.run_id != OLD.run_id
  OR NEW.event != OLD.event
  OR NEW.actor != OLD.actor
  OR NEW.detail != OLD.detail
  OR NEW.tenant_id != OLD.tenant_id
  OR NEW.timestamp != OLD.timestamp
BEGIN
    SELECT RAISE(ABORT, 'WORM violation: trace content fields cannot be updated');
END;

-- WORM protection: prevent DELETE on trace table. Audit trace records are
-- append-only and must never be removed.
CREATE TRIGGER IF NOT EXISTS worm_prevent_trace_delete
BEFORE DELETE ON trace
BEGIN
    SELECT RAISE(ABORT, 'WORM violation: trace records cannot be deleted');
END;

-- approvals: approval records (multi-level approval chain).
CREATE TABLE IF NOT EXISTS approvals (
    id         TEXT    PRIMARY KEY,
    run_id     TEXT    NOT NULL,
    level      TEXT    NOT NULL,                     -- low|medium|high|critical
    approver   TEXT    NOT NULL,
    status     TEXT    NOT NULL,                     -- pending|approved|rejected|timeout
    comment    TEXT    NOT NULL DEFAULT '',
    timeout_at DATETIME,
    acted_at   DATETIME,
    plan_hash  TEXT    NOT NULL DEFAULT '',          -- D-1 v2: plan the approval attests to ('' = legacy, any plan)
    revision   INTEGER NOT NULL DEFAULT 0,           -- D-1 v2: optimistic-lock version for concurrent decisions
    tenant_id  TEXT    NOT NULL DEFAULT '',           -- v6: mirrors runs.tenant_id
    FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_approvals_run_id    ON approvals (run_id);
CREATE INDEX IF NOT EXISTS idx_approvals_status    ON approvals (status);
CREATE INDEX IF NOT EXISTS idx_approvals_approver  ON approvals (approver);
CREATE INDEX IF NOT EXISTS idx_approvals_tenant    ON approvals (tenant_id);

-- locks: mutex locks with TTL (target-host level).
--
-- DELIBERATELY NOT TENANT-SCOPED (v6). Every other tenant-owned table carries
-- tenant_id; this one must not. A lock guards a physical host, and a host is
-- one machine no matter which tenant may change it: if locks were scoped per
-- tenant, tenant A holding host:db-1 and tenant B holding host:db-1 would be
-- two different rows and both would be admitted, which is precisely the
-- concurrent-change collision the lock exists to prevent. Host exclusion is
-- therefore global by design — an isolation bug in the safe direction.
CREATE TABLE IF NOT EXISTS locks (
    id           TEXT    PRIMARY KEY,
    scope        TEXT    NOT NULL,                   -- e.g. host:<hostname> or run:<run_id>
    owner        TEXT    NOT NULL,                   -- run_id or process identifier
    ttl_seconds  INTEGER NOT NULL,
    acquired_at  DATETIME NOT NULL,
    expires_at   DATETIME NOT NULL,
    UNIQUE (scope)
);

CREATE INDEX IF NOT EXISTS idx_locks_scope      ON locks (scope);
CREATE INDEX IF NOT EXISTS idx_locks_owner      ON locks (owner);
CREATE INDEX IF NOT EXISTS idx_locks_expires_at ON locks (expires_at);

-- credentials: encrypted credential references (MVP local encryption).
CREATE TABLE IF NOT EXISTS credentials (
    id             TEXT    PRIMARY KEY,
    name           TEXT    NOT NULL,
    type           TEXT    NOT NULL,                 -- ssh_key|ssh_password|winrm|vault_ref|token
    encrypted_data BLOB    NOT NULL,
    created_at     DATETIME NOT NULL,
    rotated_at     DATETIME,
    tags           TEXT    NOT NULL DEFAULT '',      -- v2: JSON map[string]string, '' = none
    tenant_id      TEXT    NOT NULL DEFAULT '',      -- v6: owning tenant (secrets must not cross tenants)
    UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS idx_credentials_name ON credentials (name);
CREATE INDEX IF NOT EXISTS idx_credentials_type ON credentials (type);
CREATE INDEX IF NOT EXISTS idx_credentials_tenant ON credentials (tenant_id);

-- audit: audit log entries (separate from trace; high-level actions).
--
-- The hash chain is GLOBAL, not per-run like trace. An audit row with an empty
-- run_id is exactly the security-relevant kind — a login, a config change, a
-- credential read — and a per-run chain could not cover it, leaving the most
-- sensitive records unprotected. Ordering is (timestamp, id): timestamp alone
-- ties when several entries land in the same clock tick, and a chain that
-- depends on tie-breaking is not reproducible.
CREATE TABLE IF NOT EXISTS audit (
    id         TEXT    PRIMARY KEY,
    run_id     TEXT    NOT NULL DEFAULT '',
    action     TEXT    NOT NULL,                     -- plan|apply|verify|rollback|approval|lock|credential|archive|login|config
    actor      TEXT    NOT NULL,
    target     TEXT    NOT NULL DEFAULT '',
    result     TEXT    NOT NULL,                     -- success|failure|denied|error
    timestamp  DATETIME NOT NULL,
    tenant_id  TEXT    NOT NULL DEFAULT '',          -- v6: owning tenant (NOT derivable — run_id may be ''); declared last, see the note on trace.tenant_id
    -- v7: the chain. Same shape as trace: each row's curr_hash covers the
    -- previous row's hash, so removing or editing any row breaks every hash
    -- after it. Empty means "not yet chained" (the row was just inserted);
    -- the builder fills them, and the WORM trigger below then makes them
    -- immutable.
    prev_hash  TEXT    NOT NULL DEFAULT '',
    curr_hash  TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_audit_run_id    ON audit (run_id);
CREATE INDEX IF NOT EXISTS idx_audit_action    ON audit (action);
CREATE INDEX IF NOT EXISTS idx_audit_actor     ON audit (actor);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit (timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_tenant    ON audit (tenant_id);
-- The chain is verified by walking (timestamp, id) in order; this index makes
-- that walk an index scan instead of a sort.
CREATE INDEX IF NOT EXISTS idx_audit_chain     ON audit (timestamp, id);

-- WORM protection for audit. This closes the gap the hash chain alone leaves:
-- without a database-level guard, a DBA can delete the tampered row outright
-- and the chain would verify on the shortened sequence. (The chain detects
-- edits; the trigger prevents both edits and deletes.)
--
-- prev_hash/curr_hash ARE updatable, exactly as on trace, because the chain
-- builder has to write them after the row is inserted. Everything else is
-- immutable.
CREATE TRIGGER IF NOT EXISTS worm_prevent_audit_update
BEFORE UPDATE ON audit
WHEN NEW.id != OLD.id
  OR NEW.run_id != OLD.run_id
  OR NEW.action != OLD.action
  OR NEW.actor != OLD.actor
  OR NEW.target != OLD.target
  OR NEW.result != OLD.result
  OR NEW.tenant_id != OLD.tenant_id
  OR NEW.timestamp != OLD.timestamp
BEGIN
    SELECT RAISE(ABORT, 'WORM violation: audit content fields cannot be updated');
END;

CREATE TRIGGER IF NOT EXISTS worm_prevent_audit_delete
BEFORE DELETE ON audit
BEGIN
    SELECT RAISE(ABORT, 'WORM violation: audit records cannot be deleted');
END;

-- ---------------------------------------------------------------------------
-- Inventory: managed target hosts and hierarchical groups (v1.11)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_groups (
    id         TEXT    PRIMARY KEY,
    name       TEXT    NOT NULL UNIQUE,          -- path-style name, e.g. "prod/db"
    parent_id  TEXT,
    created_at TIMESTAMP NOT NULL,
    tenant_id  TEXT    NOT NULL DEFAULT ''      -- v6: owning tenant
);

CREATE INDEX IF NOT EXISTS idx_inventory_groups_tenant ON inventory_groups (tenant_id);

CREATE TABLE IF NOT EXISTS targets (
    id              TEXT    PRIMARY KEY,
    hostname        TEXT    NOT NULL,             -- address (IP or DNS name)
    port            INTEGER NOT NULL DEFAULT 22,
    channel_type    TEXT    NOT NULL DEFAULT 'ssh',   -- ssh|winrm
    credential_ref  TEXT    NOT NULL DEFAULT '',
    labels          TEXT    NOT NULL DEFAULT '{}',    -- JSON object {"env":"prod"}
    group_id        TEXT,
    status          TEXT    NOT NULL DEFAULT 'active', -- active|frozen|retired
    reachable       INTEGER NOT NULL DEFAULT 0,
    last_checked_at TIMESTAMP,
    created_at      TIMESTAMP NOT NULL,
    tenant_id       TEXT    NOT NULL DEFAULT '',      -- v6: owning tenant
    -- UNIQUE stays table-wide: two tenants may not both register the same
    -- host address, because a host is one physical machine regardless of
    -- which tenant is allowed to change it.
    UNIQUE (hostname, port),
    FOREIGN KEY (group_id) REFERENCES inventory_groups (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_targets_group  ON targets (group_id);
CREATE INDEX IF NOT EXISTS idx_targets_status ON targets (status);
CREATE INDEX IF NOT EXISTS idx_targets_tenant ON targets (tenant_id);

-- run_assignment: cross-node dispatch assignments (design-cluster-dispatch.md).
-- One active assignment per run (run_id PK). Records which worker node was
-- dispatched to execute an approved run, the monotonic epoch that changes on
-- every reassignment, and the terminal outcome. Forward-compatible with a
-- future batch-level model: the UNIQUE(run_id, epoch) constraint keeps history,
-- and the PK can be widened to (run_id, batch_no) without touching existing rows.
CREATE TABLE IF NOT EXISTS run_assignment (
    run_id      TEXT    PRIMARY KEY,
    owner_node  TEXT    NOT NULL,
    epoch       BIGINT  NOT NULL,
    state       TEXT    NOT NULL,               -- pending | executing | done | interrupted
    result      TEXT    NOT NULL DEFAULT '',    -- completed | failed | rolled_back | ''
    assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tenant_id   TEXT    NOT NULL DEFAULT '',    -- v6: mirrors runs.tenant_id
    UNIQUE (run_id, epoch)
);

CREATE INDEX IF NOT EXISTS idx_assignment_owner_state ON run_assignment (owner_node, state);
CREATE INDEX IF NOT EXISTS idx_assignment_state ON run_assignment (state);
CREATE INDEX IF NOT EXISTS idx_assignment_tenant ON run_assignment (tenant_id);

-- ---------------------------------------------------------------------------
-- Agent registry (v8): the LEVEE agents that have registered with the master.
--
-- Persisted because the registry was a map inside whichever process built it
-- (internal/agent/registry.go): an agent registered against the daemon was
-- invisible to every other process, so `levee agent list` always came back
-- empty. One table, read by the gRPC service and the CLI alike.
--
-- NOT tenant-scoped, exactly like `locks` above: an agent is one process
-- serving the whole deployment, and state.Agent (internal/state/agents.go) has
-- no tenant to store. The decision is recorded in the
-- nonTenantOwnedTables checklist in legacy_v1_test.go, which the
-- fresh-vs-upgraded shape test reads, so adding a tenant_id here is a red
-- test rather than a silent drift.
--
-- capabilities is a JSON array in TEXT, the way params and labels are: TEXT
-- validated by the application, never a delimiter-joined list, so a capability
-- whose name contains a comma survives the round trip. '[]' is the only
-- spelling of "none" — see encodeAgentCapabilities for why '' and 'null'
-- fabricate a phantom empty capability on the way back out.
--
-- last_heartbeat is nullable on purpose: NULL means "no heartbeat has ever
-- arrived" (Agent.LastHeartbeat's zero value). NOT NULL with a default would
-- make a never-seen agent look alive at the instant its row was created.
--
-- status is free text for the same reason runs.status and cluster_nodes.status
-- are: the state layer stores what the caller validated. In play today are
-- idle | busy | draining | offline, plus registered (agent.StatusRegistered).
CREATE TABLE IF NOT EXISTS agents (
    id                TEXT    PRIMARY KEY,
    address           TEXT    NOT NULL,                          -- host:port the agent listens on
    capabilities      TEXT    NOT NULL DEFAULT '[]',             -- JSON encoded []string, '[]' = none
    status            TEXT    NOT NULL DEFAULT 'idle',           -- caller-owned vocabulary, see the note above
    last_heartbeat    DATETIME,                                  -- NULL = never heartbeated
    registered_at     DATETIME NOT NULL,                         -- first registration, kept across re-registers
    active_tasks      INTEGER NOT NULL DEFAULT 0,
    completed_tasks   INTEGER NOT NULL DEFAULT 0,
    failed_tasks      INTEGER NOT NULL DEFAULT 0,
    max_concurrent    INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_agents_status ON agents (status);