// Package agent implements the LEVEE Agent mode for distributed execution.
//
// An Agent is a常驻 process that registers with the master node, receives
// task assignments, executes them locally, and reports results back. The
// agent package is transport-agnostic: it talks to the master through a
// MasterClient interface so that the gRPC wiring can be swapped out or
// substituted with an in-memory implementation in tests.
//
// The package is organised around four files:
//
//   - executor.go: Task / Result types and the AgentExecutor that runs tasks
//     locally by delegating to the internal/executor module framework.
//   - heartbeat.go: the Heartbeat payload and the periodic sender loop.
//   - registry.go: the AgentRegistry kept on the master side that tracks
//     every registered agent, its capabilities and its current load.
//   - agent.go: the Agent struct itself, tying registration, heartbeat and
//     task execution into a single lifecycle managed by Start / Stop.
package agent

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/nexus/levee/internal/executor"
)

// Task is the unit of work that a master dispatches to an agent. It is
// transport-agnostic: the agent resolves Module + Action against the local
// executor registry and runs it against the embedded target host.
//
// Fields are intentionally value types so that Task can be marshalled over
// the wire (gRPC, JSON, ...) without losing information.
type Task struct {
	// ID is the unique task identifier, typically a UUID generated by the
	// scheduler. It is used to correlate Result replies with Task dispatches.
	ID string `json:"id"`

	// RunID is the LEVEE change-run this task belongs to. Multiple tasks
	// from the same run may be fanned out across many agents.
	RunID string `json:"run_id"`

	// BatchID is the batch within the run that owns this task. Batches are
	// the scheduling unit used by the batch controller; an agent does not
	// interpret the value but echoes it back in the Result.
	BatchID string `json:"batch_id"`

	// TargetHost is the remote host this task should act on. When the agent
	// is running in "local" mode (no SSH), TargetHost is "localhost" and
	// the task is executed in-process.
	TargetHost string `json:"target_host"`

	// Module is the executor module name, e.g. "shell", "file", "pkg",
	// "svc", "user". The agent must have the corresponding module
	// registered in its local executor.
	Module string `json:"module"`

	// Action is the module-specific verb, e.g. "exec" for shell, "copy"
	// for file, "install" for pkg. The module rejects unknown actions.
	Action string `json:"action"`

	// Args is the module-specific argument map. The agent does not
	// interpret the contents; they are passed verbatim to the module.
	Args map[string]any `json:"args"`

	// Timeout is the per-task execution budget. Zero means "no explicit
	// timeout"; the agent will still honour the context deadline set by
	// the caller of Execute.
	Timeout time.Duration `json:"timeout"`
}

// Result is the outcome of executing a single Task. Every Task dispatched
// to an agent yields exactly one Result, regardless of success or failure.
type Result struct {
	// TaskID echoes Task.ID so that the master can correlate the reply.
	TaskID string `json:"task_id"`

	// RunID echoes Task.RunID for convenience.
	RunID string `json:"run_id"`

	// BatchID echoes Task.BatchID for convenience.
	BatchID string `json:"batch_id"`

	// AgentID is the ID of the agent that produced this result.
	AgentID string `json:"agent_id"`

	// Success is true when ExitCode == 0 and Error is empty. It is the
	// single boolean the scheduler consults when deciding whether to
	// advance, retry or rollback.
	Success bool `json:"success"`

	// ExitCode is the remote process exit code. 0 means success; non-zero
	// means the command ran but failed. A negative value means the agent
	// could not run the task at all (e.g. unknown module).
	ExitCode int `json:"exit_code"`

	// Stdout is the captured standard output of the remote process.
	Stdout string `json:"stdout"`

	// Stderr is the captured standard error of the remote process.
	Stderr string `json:"stderr"`

	// Duration is the wall-clock time spent inside Execute, measured by
	// the agent executor wrapper.
	Duration time.Duration `json:"duration"`

	// Error is the human-readable error message when the agent could not
	// run the task at all (e.g. unknown module, channel broken, timeout).
	// It is empty when Success is true.
	Error string `json:"error"`
}

// AgentExecutor runs Task values locally by delegating to the
// internal/executor module framework. It enforces a MaxConcurrent bound
// so that a single agent cannot overload its host when the master fans
// out a large batch.
//
// AgentExecutor is safe for concurrent use. The zero value is not usable;
// callers must use NewAgentExecutor.
type AgentExecutor struct {
	// maxConcurrent is the upper bound on simultaneously running tasks.
	// It is treated as immutable after NewAgentExecutor returns; the
	// semaphore is pre-allocated accordingly.
	maxConcurrent int

	// exec is the underlying executor.Executor used to dispatch module
	// invocations. It is typically executor.DefaultExecutor() populated
	// by the module init() functions.
	exec *executor.Executor

	// sem is a buffered channel used as a counting semaphore to enforce
	// maxConcurrent. A send reserves a slot; a receive releases it.
	sem chan struct{}

	// stats tracks cumulative counters used by heartbeat reporting.
	stats struct {
		completed atomic.Int64
		failed    atomic.Int64
		active    atomic.Int64
	}

	// runTask is the function that actually executes a single task. It
	// is swapped in tests to bypass the real executor. When nil the
	// executor is used.
	runTask func(ctx context.Context, task Task) Result

	mu sync.Mutex
}

// NewAgentExecutor returns an AgentExecutor bound to the given executor
// and concurrency limit. If exec is nil, executor.DefaultExecutor() is
// used. If maxConcurrent <= 0 it defaults to 1.
func NewAgentExecutor(maxConcurrent int, exec *executor.Executor) *AgentExecutor {
	if maxConcurrent <= 0 {
		maxConcurrent = 1
	}
	if exec == nil {
		exec = executor.DefaultExecutor()
	}
	return &AgentExecutor{
		maxConcurrent: maxConcurrent,
		exec:          exec,
		sem:           make(chan struct{}, maxConcurrent),
	}
}

// Execute runs a single task to completion. It enforces the concurrency
// limit, applies the task timeout, and translates the executor output
// into a Result. Execute never returns an error: every failure path is
// captured inside the Result so that the caller (typically the agent
// task loop) can simply forward the Result to the master.
//
// Execute blocks until the task finishes or the context is cancelled.
// A cancelled context produces a Result with Success=false and Error
// set to the context error.
func (e *AgentExecutor) Execute(ctx context.Context, task Task) Result {
	// Acquire a concurrency slot. On context cancellation release is
	// guaranteed by the deferred receive.
	select {
	case e.sem <- struct{}{}:
		defer func() { <-e.sem }()
	case <-ctx.Done():
		return Result{
			TaskID:  task.ID,
			RunID:   task.RunID,
			BatchID: task.BatchID,
			Success: false,
			Error:   ctx.Err().Error(),
		}
	}

	e.stats.active.Add(1)
	defer e.stats.active.Add(-1)

	// Apply per-task timeout if set.
	runCtx := ctx
	if task.Timeout > 0 {
		var cancel context.CancelFunc
		runCtx, cancel = context.WithTimeout(ctx, task.Timeout)
		defer cancel()
	}

	start := time.Now()
	var res Result
	if e.runTask != nil {
		res = e.runTask(runCtx, task)
	} else {
		res = e.executeWithExecutor(runCtx, task)
	}
	res.Duration = time.Since(start)
	res.TaskID = task.ID
	res.RunID = task.RunID
	res.BatchID = task.BatchID

	if res.Success {
		e.stats.completed.Add(1)
	} else {
		e.stats.failed.Add(1)
	}
	return res
}

// executeWithExecutor is the production path: it dispatches through the
// underlying executor and translates the result. It does not touch the
// semaphore or the stats counters; those are handled by Execute.
func (e *AgentExecutor) executeWithExecutor(ctx context.Context, task Task) Result {
	out, err := e.exec.Execute(ctx, task.Module, task.Action, executor.ModuleInput{
		Action: task.Action,
		Args:   task.Args,
	})

	res := Result{}
	if err != nil {
		res.Success = false
		res.Error = err.Error()
		res.ExitCode = -1
		return res
	}
	if out == nil {
		res.Success = false
		res.Error = "agent: executor returned nil output without error"
		res.ExitCode = -1
		return res
	}
	res.ExitCode = out.ExitCode
	res.Stdout = out.Stdout
	res.Stderr = out.Stderr
	res.Success = out.ExitCode == 0
	return res
}

// ExecuteBatch runs a slice of tasks concurrently, bounded by
// MaxConcurrent, and returns the results in the same order as the input
// tasks. ExecuteBatch is a convenience wrapper around Execute; it does
// not introduce any additional ordering or retry semantics.
//
// The returned slice always has the same length as tasks; a nil task
// entry yields a zero-valued Result.
func (e *AgentExecutor) ExecuteBatch(ctx context.Context, tasks []Task) []Result {
	if len(tasks) == 0 {
		return nil
	}
	results := make([]Result, len(tasks))
	var wg sync.WaitGroup
	for i, task := range tasks {
		wg.Add(1)
		go func(idx int, t Task) {
			defer wg.Done()
			results[idx] = e.Execute(ctx, t)
		}(i, task)
	}
	wg.Wait()
	return results
}

// Stats returns a snapshot of the executor's cumulative counters. It is
// safe to call concurrently with Execute. The returned struct is a value
// copy and may be stale by the time the caller reads it; that is
// acceptable for heartbeat reporting which only needs approximate
// values.
type ExecutorStats struct {
	Completed int64
	Failed    int64
	Active    int64
}

// Stats returns the current cumulative counter snapshot.
func (e *AgentExecutor) Stats() ExecutorStats {
	return ExecutorStats{
		Completed: e.stats.completed.Load(),
		Failed:    e.stats.failed.Load(),
		Active:    e.stats.active.Load(),
	}
}

// MaxConcurrent returns the configured concurrency limit. It is exposed
// so that the heartbeat reporter can advertise the agent's capacity.
func (e *AgentExecutor) MaxConcurrent() int {
	return e.maxConcurrent
}

// SetRunTaskHook installs a function that overrides the default
// executor dispatch. It is intended for tests and must not be called
// concurrently with Execute. Passing nil restores the default behaviour.
func (e *AgentExecutor) SetRunTaskHook(fn func(ctx context.Context, task Task) Result) {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.runTask = fn
}

// formatTaskError produces a stable error string for logging. It is
// kept here rather than inline so that future formatting changes have
// a single point of modification.
func formatTaskError(task Task, reason string) string {
	return fmt.Sprintf("agent: task %s (%s/%s on %s): %s",
		task.ID, task.Module, task.Action, task.TargetHost, strings.TrimSpace(reason))
}
