//go:build !proto_regenerate

// Code generated by hand for LEVEE. DO NOT EDIT (regenerate with protoc
// when available).
//
// Message types for InventoryService (v1.11 asset-management additions):
// hierarchical target groups, bulk YAML import, target lifecycle status and
// per-target change history. Authored by hand following the same pattern as
// levee_extra.pb.go: minimal Reset/String/ProtoMessage trio, struct tags
// mirroring proto field numbers.

package pb

// Group is a hierarchical inventory group. Names are unique and path-style.
type Group struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId string `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return messageString(m) }
func (m *Group) ProtoMessage()  {}

type CreateGroupRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId string `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return messageString(m) }
func (m *CreateGroupRequest) ProtoMessage()  {}

type ListGroupsRequest struct{}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return messageString(m) }
func (m *ListGroupsRequest) ProtoMessage()  {}

type ListGroupsResponse struct {
	Groups []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return messageString(m) }
func (m *ListGroupsResponse) ProtoMessage()  {}

type DeleteGroupRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return messageString(m) }
func (m *DeleteGroupRequest) ProtoMessage()  {}

type DeleteGroupResponse struct{}

func (m *DeleteGroupResponse) Reset()         { *m = DeleteGroupResponse{} }
func (m *DeleteGroupResponse) String() string { return messageString(m) }
func (m *DeleteGroupResponse) ProtoMessage()  {}

// ImportTargetsRequest carries the raw YAML content of an inventory file.
type ImportTargetsRequest struct {
	YamlContent string `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	// DefaultGroup optionally assigns every imported target lacking an
	// explicit group to this group name (created when missing).
	DefaultGroup string `protobuf:"bytes,2,opt,name=default_group,json=defaultGroup,proto3" json:"default_group,omitempty"`
}

func (m *ImportTargetsRequest) Reset()         { *m = ImportTargetsRequest{} }
func (m *ImportTargetsRequest) String() string { return messageString(m) }
func (m *ImportTargetsRequest) ProtoMessage()  {}

type ImportTargetsResponse struct {
	Created int32    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated int32    `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Failed  int32    `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors  []string `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (m *ImportTargetsResponse) Reset()         { *m = ImportTargetsResponse{} }
func (m *ImportTargetsResponse) String() string { return messageString(m) }
func (m *ImportTargetsResponse) ProtoMessage()  {}

type SetTargetStatusRequest struct {
	TargetId string `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Status must be one of active|frozen|retired.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *SetTargetStatusRequest) Reset()         { *m = SetTargetStatusRequest{} }
func (m *SetTargetStatusRequest) String() string { return messageString(m) }
func (m *SetTargetStatusRequest) ProtoMessage()  {}

type SetTargetStatusResponse struct {
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *SetTargetStatusResponse) Reset()         { *m = SetTargetStatusResponse{} }
func (m *SetTargetStatusResponse) String() string { return messageString(m) }
func (m *SetTargetStatusResponse) ProtoMessage()  {}

// TargetHistoryEntry is one change run that executed on the queried host.
type TargetHistoryEntry struct {
	RunId        string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowName string `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Status       string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Creator      string `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt    int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *TargetHistoryEntry) Reset()         { *m = TargetHistoryEntry{} }
func (m *TargetHistoryEntry) String() string { return messageString(m) }
func (m *TargetHistoryEntry) ProtoMessage()  {}

type TargetHistoryRequest struct {
	// Host is the address (targets.hostname) to look up runs for.
	Host  string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Limit int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *TargetHistoryRequest) Reset()         { *m = TargetHistoryRequest{} }
func (m *TargetHistoryRequest) String() string { return messageString(m) }
func (m *TargetHistoryRequest) ProtoMessage()  {}

type TargetHistoryResponse struct {
	Entries []*TargetHistoryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (m *TargetHistoryResponse) Reset()         { *m = TargetHistoryResponse{} }
func (m *TargetHistoryResponse) String() string { return messageString(m) }
func (m *TargetHistoryResponse) ProtoMessage()  {}

// --- Getters (mirror protoc-gen-go output; nil-safe) -----------------------

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}
func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}
func (m *Group) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}
func (m *CreateGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}
func (m *CreateGroupRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}
func (m *DeleteGroupRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}
func (m *ImportTargetsRequest) GetYamlContent() string {
	if m != nil {
		return m.YamlContent
	}
	return ""
}
func (m *ImportTargetsRequest) GetDefaultGroup() string {
	if m != nil {
		return m.DefaultGroup
	}
	return ""
}
func (m *SetTargetStatusRequest) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}
func (m *SetTargetStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}
func (m *TargetHistoryRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}
func (m *TargetHistoryRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}
func (m *ListGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}
func (m *SetTargetStatusResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}
func (m *SetTargetStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}
func (m *ImportTargetsResponse) GetCreated() int32 {
	if m != nil {
		return m.Created
	}
	return 0
}
func (m *ImportTargetsResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}
func (m *TargetHistoryResponse) GetEntries() []*TargetHistoryEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}
func (m *TargetHistoryEntry) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}
func (m *TargetHistoryEntry) GetWorkflowName() string {
	if m != nil {
		return m.WorkflowName
	}
	return ""
}
