// Code generated by hand for LEVEE. DO NOT EDIT (regenerate with
// protoc-gen-go-grpc when available).
//
// gRPC service definition for InventoryService, mirroring the structure of
// levee_extra_grpc.pb.go: Server interface, Unimplemented stub, Register
// function, per-RPC handlers and ServiceDesc. Client side omitted — LEVEE
// only serves these; tests use in-process servers.

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

// ===========================================================================
// InventoryService
// ===========================================================================

const (
	InventoryService_ListGroups_FullMethodName     = "/levee.InventoryService/ListGroups"
	InventoryService_CreateGroup_FullMethodName    = "/levee.InventoryService/CreateGroup"
	InventoryService_DeleteGroup_FullMethodName    = "/levee.InventoryService/DeleteGroup"
	InventoryService_ImportTargets_FullMethodName  = "/levee.InventoryService/ImportTargets"
	InventoryService_SetTargetStatus_FullMethodName = "/levee.InventoryService/SetTargetStatus"
	InventoryService_TargetHistory_FullMethodName   = "/levee.InventoryService/TargetHistory"
)

type InventoryServiceServer interface {
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*Group, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error)
	ImportTargets(context.Context, *ImportTargetsRequest) (*ImportTargetsResponse, error)
	SetTargetStatus(context.Context, *SetTargetStatusRequest) (*SetTargetStatusResponse, error)
	TargetHistory(context.Context, *TargetHistoryRequest) (*TargetHistoryResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedInventoryServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedInventoryServiceServer) DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedInventoryServiceServer) ImportTargets(context.Context, *ImportTargetsRequest) (*ImportTargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportTargets not implemented")
}
func (UnimplementedInventoryServiceServer) SetTargetStatus(context.Context, *SetTargetStatusRequest) (*SetTargetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTargetStatus not implemented")
}
func (UnimplementedInventoryServiceServer) TargetHistory(context.Context, *TargetHistoryRequest) (*TargetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TargetHistory not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}

// RegisterInventoryServiceServer registers the service on a gRPC server.
func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	s.RegisterService(&_InventoryService_serviceDesc, srv)
}

func inventoryHandlerListGroups(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InventoryService_ListGroups_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(InventoryServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	})
}

func inventoryHandlerCreateGroup(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InventoryService_CreateGroup_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(InventoryServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	})
}

func inventoryHandlerDeleteGroup(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InventoryService_DeleteGroup_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(InventoryServiceServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	})
}

func inventoryHandlerImportTargets(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ImportTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ImportTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InventoryService_ImportTargets_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(InventoryServiceServer).ImportTargets(ctx, req.(*ImportTargetsRequest))
	})
}

func inventoryHandlerSetTargetStatus(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(SetTargetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).SetTargetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InventoryService_SetTargetStatus_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(InventoryServiceServer).SetTargetStatus(ctx, req.(*SetTargetStatusRequest))
	})
}

func inventoryHandlerTargetHistory(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(TargetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).TargetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InventoryService_TargetHistory_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(InventoryServiceServer).TargetHistory(ctx, req.(*TargetHistoryRequest))
	})
}

var _InventoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "levee.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "ListGroups", Handler: inventoryHandlerListGroups},
		{MethodName: "CreateGroup", Handler: inventoryHandlerCreateGroup},
		{MethodName: "DeleteGroup", Handler: inventoryHandlerDeleteGroup},
		{MethodName: "ImportTargets", Handler: inventoryHandlerImportTargets},
		{MethodName: "SetTargetStatus", Handler: inventoryHandlerSetTargetStatus},
		{MethodName: "TargetHistory", Handler: inventoryHandlerTargetHistory},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "levee.proto",
}
