//go:build !proto_regenerate

// Code generated by hand for LEVEE. DO NOT EDIT (regenerate with
// protoc-gen-go-grpc when available).
//
// This file contains the gRPC service definitions for AlertService,
// DiagnosisService and ConversationService added in C5 (task 132). The
// structure mirrors protoc-gen-go-grpc output: each service has a Server
// interface, an Unimplemented*Server stub, a Register*Server function, a
// handler per RPC and a ServiceDesc. The client side is omitted because
// LEVEE only acts as a server for these services; clients are tested via
// grpc.NewClient against an in-process server.
//
// Because the messages in levee_extra.pb.go do not implement
// proto.Message Reflect, the codec used for these RPCs is the
// google.golang.org/grpc/protobuf codec (registered by default). The
// hand-written messages implement the legacy proto.Message interface
// (Reset/String/ProtoMessage) which is sufficient for the codec to
// marshal/unmarshal them via the json/struct fallback path.

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Compile-time assertion that this file is compatible with the grpc package.
const _ = grpc.SupportPackageIsVersion9

// ===========================================================================
// AlertService
// ===========================================================================

const (
	AlertService_ReceiveAlert_FullMethodName    = "/levee.AlertService/ReceiveAlert"
	AlertService_GetAlertStatus_FullMethodName  = "/levee.AlertService/GetAlertStatus"
	AlertService_SubscribeAlerts_FullMethodName = "/levee.AlertService/SubscribeAlerts"
)

// AlertServiceServer is the server API for the AlertService service.
// All implementations must embed UnimplementedAlertServiceServer for
// forward compatibility.
type AlertServiceServer interface {
	// ReceiveAlert ingests a single alert into the gateway.
	ReceiveAlert(context.Context, *AlertMessage) (*AlertResponse, error)
	// GetAlertStatus returns the current status of an alert by id.
	GetAlertStatus(context.Context, *GetAlertStatusRequest) (*AlertStatus, error)
	// SubscribeAlerts opens a server-stream of alerts matching the filter.
	SubscribeAlerts(*SubscribeRequest, AlertService_SubscribeAlertsServer) error
	mustEmbedUnimplementedAlertServiceServer()
}

// AlertService_SubscribeAlertsServer is the server stream for SubscribeAlerts.
type AlertService_SubscribeAlertsServer = grpc.ServerStreamingServer[AlertMessage]

// UnimplementedAlertServiceServer must be embedded to have forward
// compatible implementations. Embed by value, not by pointer.
type UnimplementedAlertServiceServer struct{}

// ReceiveAlert returns Unimplemented.
func (UnimplementedAlertServiceServer) ReceiveAlert(context.Context, *AlertMessage) (*AlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveAlert not implemented")
}

// GetAlertStatus returns Unimplemented.
func (UnimplementedAlertServiceServer) GetAlertStatus(context.Context, *GetAlertStatusRequest) (*AlertStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlertStatus not implemented")
}

// SubscribeAlerts returns Unimplemented.
func (UnimplementedAlertServiceServer) SubscribeAlerts(*SubscribeRequest, AlertService_SubscribeAlertsServer) error {
	return status.Error(codes.Unimplemented, "method SubscribeAlerts not implemented")
}

func (UnimplementedAlertServiceServer) mustEmbedUnimplementedAlertServiceServer() {}
func (UnimplementedAlertServiceServer) testEmbeddedByValue()                      {}

// UnsafeAlertServiceServer may be embedded to opt out of forward
// compatibility for this service. Use of this interface is not
// recommended, as added methods to AlertServiceServer will result in
// compilation errors.
type UnsafeAlertServiceServer interface {
	mustEmbedUnimplementedAlertServiceServer()
}

// RegisterAlertServiceServer registers srv on s.
func RegisterAlertServiceServer(s grpc.ServiceRegistrar, srv AlertServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertService_ServiceDesc, srv)
}

func _AlertService_ReceiveAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).ReceiveAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_ReceiveAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).ReceiveAlert(ctx, req.(*AlertMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_GetAlertStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).GetAlertStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_GetAlertStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).GetAlertStatus(ctx, req.(*GetAlertStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_SubscribeAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlertServiceServer).SubscribeAlerts(m, &grpc.GenericServerStream[SubscribeRequest, AlertMessage]{ServerStream: stream})
}

// AlertService_ServiceDesc is the grpc.ServiceDesc for AlertService.
var AlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levee.AlertService",
	HandlerType: (*AlertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveAlert",
			Handler:    _AlertService_ReceiveAlert_Handler,
		},
		{
			MethodName: "GetAlertStatus",
			Handler:    _AlertService_GetAlertStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeAlerts",
			Handler:       _AlertService_SubscribeAlerts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "levee.proto",
}

// ===========================================================================
// DiagnosisService
// ===========================================================================

const (
	DiagnosisService_Diagnose_FullMethodName     = "/levee.DiagnosisService/Diagnose"
	DiagnosisService_GetDiagnosis_FullMethodName = "/levee.DiagnosisService/GetDiagnosis"
)

// DiagnosisServiceServer is the server API for the DiagnosisService.
type DiagnosisServiceServer interface {
	// Diagnose runs a fresh diagnosis on the given target.
	Diagnose(context.Context, *DiagnoseRequest) (*DiagnosticReportMessage, error)
	// GetDiagnosis returns a previously stored diagnosis report by id.
	GetDiagnosis(context.Context, *GetDiagnosisRequest) (*DiagnosticReportMessage, error)
	mustEmbedUnimplementedDiagnosisServiceServer()
}

// UnimplementedDiagnosisServiceServer must be embedded by value.
type UnimplementedDiagnosisServiceServer struct{}

// Diagnose returns Unimplemented.
func (UnimplementedDiagnosisServiceServer) Diagnose(context.Context, *DiagnoseRequest) (*DiagnosticReportMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Diagnose not implemented")
}

// GetDiagnosis returns Unimplemented.
func (UnimplementedDiagnosisServiceServer) GetDiagnosis(context.Context, *GetDiagnosisRequest) (*DiagnosticReportMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiagnosis not implemented")
}

func (UnimplementedDiagnosisServiceServer) mustEmbedUnimplementedDiagnosisServiceServer() {}
func (UnimplementedDiagnosisServiceServer) testEmbeddedByValue()                          {}

// UnsafeDiagnosisServiceServer may be embedded to opt out of forward
// compatibility for this service.
type UnsafeDiagnosisServiceServer interface {
	mustEmbedUnimplementedDiagnosisServiceServer()
}

// RegisterDiagnosisServiceServer registers srv on s.
func RegisterDiagnosisServiceServer(s grpc.ServiceRegistrar, srv DiagnosisServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiagnosisService_ServiceDesc, srv)
}

func _DiagnosisService_Diagnose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnoseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).Diagnose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagnosisService_Diagnose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).Diagnose(ctx, req.(*DiagnoseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_GetDiagnosis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiagnosisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).GetDiagnosis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagnosisService_GetDiagnosis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).GetDiagnosis(ctx, req.(*GetDiagnosisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiagnosisService_ServiceDesc is the grpc.ServiceDesc for DiagnosisService.
var DiagnosisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levee.DiagnosisService",
	HandlerType: (*DiagnosisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Diagnose",
			Handler:    _DiagnosisService_Diagnose_Handler,
		},
		{
			MethodName: "GetDiagnosis",
			Handler:    _DiagnosisService_GetDiagnosis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "levee.proto",
}

// ===========================================================================
// ConversationService
// ===========================================================================

const (
	ConversationService_SendMessage_FullMethodName           = "/levee.ConversationService/SendMessage"
	ConversationService_SubscribeConversation_FullMethodName = "/levee.ConversationService/SubscribeConversation"
)

// ConversationServiceServer is the server API for the ConversationService.
type ConversationServiceServer interface {
	// SendMessage sends a single user message and returns the engine reply.
	SendMessage(context.Context, *SendMessageRequest) (*ReplyMessage, error)
	// SubscribeConversation opens a server-stream of replies for the
	// given filter (typically a session id encoded in Source).
	SubscribeConversation(*SubscribeRequest, ConversationService_SubscribeConversationServer) error
	mustEmbedUnimplementedConversationServiceServer()
}

// ConversationService_SubscribeConversationServer is the server stream for
// SubscribeConversation.
type ConversationService_SubscribeConversationServer = grpc.ServerStreamingServer[ReplyMessage]

// UnimplementedConversationServiceServer must be embedded by value.
type UnimplementedConversationServiceServer struct{}

// SendMessage returns Unimplemented.
func (UnimplementedConversationServiceServer) SendMessage(context.Context, *SendMessageRequest) (*ReplyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}

// SubscribeConversation returns Unimplemented.
func (UnimplementedConversationServiceServer) SubscribeConversation(*SubscribeRequest, ConversationService_SubscribeConversationServer) error {
	return status.Error(codes.Unimplemented, "method SubscribeConversation not implemented")
}

func (UnimplementedConversationServiceServer) mustEmbedUnimplementedConversationServiceServer() {}
func (UnimplementedConversationServiceServer) testEmbeddedByValue()                             {}

// UnsafeConversationServiceServer may be embedded to opt out of forward
// compatibility for this service.
type UnsafeConversationServiceServer interface {
	mustEmbedUnimplementedConversationServiceServer()
}

// RegisterConversationServiceServer registers srv on s.
func RegisterConversationServiceServer(s grpc.ServiceRegistrar, srv ConversationServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConversationService_ServiceDesc, srv)
}

func _ConversationService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_SubscribeConversation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConversationServiceServer).SubscribeConversation(m, &grpc.GenericServerStream[SubscribeRequest, ReplyMessage]{ServerStream: stream})
}

// ConversationService_ServiceDesc is the grpc.ServiceDesc for
// ConversationService.
var ConversationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levee.ConversationService",
	HandlerType: (*ConversationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _ConversationService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeConversation",
			Handler:       _ConversationService_SubscribeConversation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "levee.proto",
}
