// Code generated by hand for LEVEE. DO NOT EDIT (regenerate with protoc
// when available).
//
// This file contains the message types for the AlertService,
// DiagnosisService and ConversationService added in C5 (task 132).
// Because protoc is not available in the build environment, the types are
// authored by hand and implement the proto.Message interface via the
// minimal Reset/String/ProtoMessage trio. The protobuf struct tags mirror
// the field numbers in proto/levee.proto so the messages can be serialised
// by the protobuf runtime once the generated reflection metadata is added
// (or once protoc is reintroduced).
//
// The types are intentionally simple value objects: no validation, no
// computed fields. Conversion to and from the internal domain types lives
// in the service implementations (alert_service.go etc.).

package pb

import (
	"fmt"
	"reflect"
	"strings"
)

// messageString returns a debug representation of m without invoking
// m.String(). It walks the struct fields via reflect so the fmt
// formatter never sees a fmt.Stringer and therefore cannot recurse.
// Used by the hand-written String() methods below.
func messageString(m any) string {
	v := reflect.ValueOf(m)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}
	t := v.Type()
	if t.Kind() != reflect.Struct {
		return fmt.Sprintf("%v", m)
	}
	var b strings.Builder
	b.WriteString(t.Name())
	b.WriteByte('{')
	first := true
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		if !first {
			b.WriteByte(' ')
		}
		first = false
		b.WriteString(f.Name)
		b.WriteByte(':')
		fmt.Fprintf(&b, "%v", v.Field(i).Interface())
	}
	b.WriteByte('}')
	return b.String()
}

// ---------------------------------------------------------------------------
// AlertService messages
// ---------------------------------------------------------------------------

// AlertMessage is the wire representation of an alert. Named "AlertMessage"
// to avoid clashing with the alert.Alert domain type.
type AlertMessage struct {
	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source      string            `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Severity    string            `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Target      string            `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Title       string            `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Labels      map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fingerprint string            `protobuf:"bytes,8,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	StartsAt    int64             `protobuf:"varint,9,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt      int64             `protobuf:"varint,10,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Status      string            `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
}

// Reset implements proto.Message.
func (m *AlertMessage) Reset() { *m = AlertMessage{} }

// String implements proto.Message.
func (m *AlertMessage) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*AlertMessage) ProtoMessage() {}

// GetId returns the alert id.
func (m *AlertMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// GetSource returns the alert source.
func (m *AlertMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

// GetSeverity returns the alert severity.
func (m *AlertMessage) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

// GetTarget returns the alert target.
func (m *AlertMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

// GetTitle returns the alert title.
func (m *AlertMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// GetDescription returns the alert description.
func (m *AlertMessage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// GetStatus returns the alert status.
func (m *AlertMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// GetFingerprint returns the alert fingerprint.
func (m *AlertMessage) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

// GetStartsAt returns the alert start timestamp (unix seconds).
func (m *AlertMessage) GetStartsAt() int64 {
	if m != nil {
		return m.StartsAt
	}
	return 0
}

// GetEndsAt returns the alert end timestamp (unix seconds).
func (m *AlertMessage) GetEndsAt() int64 {
	if m != nil {
		return m.EndsAt
	}
	return 0
}

// GetLabels returns the alert labels.
func (m *AlertMessage) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// AlertResponse is the response from ReceiveAlert.
type AlertResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

// Reset implements proto.Message.
func (m *AlertResponse) Reset() { *m = AlertResponse{} }

// String implements proto.Message.
func (m *AlertResponse) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*AlertResponse) ProtoMessage() {}

// GetStatus returns the response status.
func (m *AlertResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// GetId returns the alert id.
func (m *AlertResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// GetReason returns the optional reason.
func (m *AlertResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// GetAlertStatusRequest is the request for GetAlertStatus.
type GetAlertStatusRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

// Reset implements proto.Message.
func (m *GetAlertStatusRequest) Reset() { *m = GetAlertStatusRequest{} }

// String implements proto.Message.
func (m *GetAlertStatusRequest) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*GetAlertStatusRequest) ProtoMessage() {}

// GetId returns the alert id.
func (m *GetAlertStatusRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// AlertStatus is the response from GetAlertStatus.
type AlertStatus struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status   string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartsAt int64  `protobuf:"varint,3,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt   int64  `protobuf:"varint,4,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Severity string `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
}

// Reset implements proto.Message.
func (m *AlertStatus) Reset() { *m = AlertStatus{} }

// String implements proto.Message.
func (m *AlertStatus) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*AlertStatus) ProtoMessage() {}

// GetId returns the alert id.
func (m *AlertStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// GetStatus returns the alert status.
func (m *AlertStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// GetSeverity returns the alert severity.
func (m *AlertStatus) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

// SubscribeRequest is the request for the streaming SubscribeAlerts and
// SubscribeConversation RPCs.
type SubscribeRequest struct {
	Severity string `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Source   string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

// Reset implements proto.Message.
func (m *SubscribeRequest) Reset() { *m = SubscribeRequest{} }

// String implements proto.Message.
func (m *SubscribeRequest) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*SubscribeRequest) ProtoMessage() {}

// GetSeverity returns the severity filter.
func (m *SubscribeRequest) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

// GetSource returns the source filter.
func (m *SubscribeRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

// ---------------------------------------------------------------------------
// DiagnosisService messages
// ---------------------------------------------------------------------------

// DiagnoseRequest is the request for Diagnose.
type DiagnoseRequest struct {
	Target         string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	AlertId        string `protobuf:"bytes,2,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	TimeoutSeconds int64  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
}

// Reset implements proto.Message.
func (m *DiagnoseRequest) Reset() { *m = DiagnoseRequest{} }

// String implements proto.Message.
func (m *DiagnoseRequest) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*DiagnoseRequest) ProtoMessage() {}

// GetTarget returns the diagnosis target.
func (m *DiagnoseRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

// GetAlertId returns the optional alert id.
func (m *DiagnoseRequest) GetAlertId() string {
	if m != nil {
		return m.AlertId
	}
	return ""
}

// GetTimeoutSeconds returns the optional timeout.
func (m *DiagnoseRequest) GetTimeoutSeconds() int64 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

// GetDiagnosisRequest is the request for GetDiagnosis.
type GetDiagnosisRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

// Reset implements proto.Message.
func (m *GetDiagnosisRequest) Reset() { *m = GetDiagnosisRequest{} }

// String implements proto.Message.
func (m *GetDiagnosisRequest) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*GetDiagnosisRequest) ProtoMessage() {}

// GetId returns the report id.
func (m *GetDiagnosisRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// DiagnosticReportMessage is the wire representation of a diagnosis report.
// Named to avoid clashing with diagnosis.DiagnosticReport.
type DiagnosticReportMessage struct {
	Id              string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Target          string            `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Trigger         string            `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	AlertId         string            `protobuf:"bytes,4,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Status          string            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RootCause       string            `protobuf:"bytes,6,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	Confidence      float64           `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Summary         string            `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	Recommendations []string          `protobuf:"bytes,9,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Errors          []string          `protobuf:"bytes,10,rep,name=errors,proto3" json:"errors,omitempty"`
	StartedAt       int64             `protobuf:"varint,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	DurationMs      int64             `protobuf:"varint,12,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Findings        []*FindingMessage `protobuf:"bytes,13,rep,name=findings,proto3" json:"findings,omitempty"`
}

// Reset implements proto.Message.
func (m *DiagnosticReportMessage) Reset() { *m = DiagnosticReportMessage{} }

// String implements proto.Message.
func (m *DiagnosticReportMessage) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*DiagnosticReportMessage) ProtoMessage() {}

// GetId returns the report id.
func (m *DiagnosticReportMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// GetTarget returns the report target.
func (m *DiagnosticReportMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

// GetStatus returns the report status.
func (m *DiagnosticReportMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// GetRootCause returns the root cause hypothesis.
func (m *DiagnosticReportMessage) GetRootCause() string {
	if m != nil {
		return m.RootCause
	}
	return ""
}

// GetSummary returns the summary.
func (m *DiagnosticReportMessage) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

// GetFindings returns the findings slice.
func (m *DiagnosticReportMessage) GetFindings() []*FindingMessage {
	if m != nil {
		return m.Findings
	}
	return nil
}

// FindingMessage is the wire representation of a diagnosis Finding.
type FindingMessage struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category    string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Severity    string `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Title       string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Evidence    string `protobuf:"bytes,6,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Suggestion  string `protobuf:"bytes,7,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
}

// Reset implements proto.Message.
func (m *FindingMessage) Reset() { *m = FindingMessage{} }

// String implements proto.Message.
func (m *FindingMessage) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*FindingMessage) ProtoMessage() {}

// GetId returns the finding id.
func (m *FindingMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// GetSeverity returns the finding severity.
func (m *FindingMessage) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

// GetTitle returns the finding title.
func (m *FindingMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// ---------------------------------------------------------------------------
// ConversationService messages
// ---------------------------------------------------------------------------

// SendMessageRequest is the request for SendMessage.
type SendMessageRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text      string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

// Reset implements proto.Message.
func (m *SendMessageRequest) Reset() { *m = SendMessageRequest{} }

// String implements proto.Message.
func (m *SendMessageRequest) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*SendMessageRequest) ProtoMessage() {}

// GetSessionId returns the session id.
func (m *SendMessageRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

// GetUserId returns the user id.
func (m *SendMessageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// GetText returns the message text.
func (m *SendMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// ReplyMessage is the wire representation of conversation.Reply.
type ReplyMessage struct {
	Text          string            `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ActionType    string            `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	ActionPayload map[string]string `protobuf:"bytes,3,rep,name=action_payload,json=actionPayload,proto3" json:"action_payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionId     string            `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

// Reset implements proto.Message.
func (m *ReplyMessage) Reset() { *m = ReplyMessage{} }

// String implements proto.Message.
func (m *ReplyMessage) String() string { return messageString(m) }

// ProtoMessage implements proto.Message.
func (*ReplyMessage) ProtoMessage() {}

// GetText returns the reply text.
func (m *ReplyMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// GetActionType returns the action type.
func (m *ReplyMessage) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

// GetSessionId returns the session id.
func (m *ReplyMessage) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}
