// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.0
// source: levee.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChangeService_CreateChange_FullMethodName   = "/levee.ChangeService/CreateChange"
	ChangeService_CloneChange_FullMethodName    = "/levee.ChangeService/CloneChange"
	ChangeService_PlanChange_FullMethodName     = "/levee.ChangeService/PlanChange"
	ChangeService_ApplyChange_FullMethodName    = "/levee.ChangeService/ApplyChange"
	ChangeService_PauseChange_FullMethodName    = "/levee.ChangeService/PauseChange"
	ChangeService_ResumeChange_FullMethodName   = "/levee.ChangeService/ResumeChange"
	ChangeService_PauseAll_FullMethodName       = "/levee.ChangeService/PauseAll"
	ChangeService_ResumeAll_FullMethodName      = "/levee.ChangeService/ResumeAll"
	ChangeService_CancelChange_FullMethodName   = "/levee.ChangeService/CancelChange"
	ChangeService_RetryChange_FullMethodName    = "/levee.ChangeService/RetryChange"
	ChangeService_RetryHost_FullMethodName      = "/levee.ChangeService/RetryHost"
	ChangeService_RollbackChange_FullMethodName = "/levee.ChangeService/RollbackChange"
	ChangeService_ApproveChange_FullMethodName  = "/levee.ChangeService/ApproveChange"
	ChangeService_RejectChange_FullMethodName   = "/levee.ChangeService/RejectChange"
	ChangeService_GetChange_FullMethodName      = "/levee.ChangeService/GetChange"
	ChangeService_ListChanges_FullMethodName    = "/levee.ChangeService/ListChanges"
	ChangeService_ArchiveChange_FullMethodName  = "/levee.ChangeService/ArchiveChange"
	ChangeService_GetLogs_FullMethodName        = "/levee.ChangeService/GetLogs"
	ChangeService_GetDiff_FullMethodName        = "/levee.ChangeService/GetDiff"
	ChangeService_GetTrace_FullMethodName       = "/levee.ChangeService/GetTrace"
	ChangeService_WatchChange_FullMethodName    = "/levee.ChangeService/WatchChange"
	ChangeService_StreamLogs_FullMethodName     = "/levee.ChangeService/StreamLogs"
)

// ChangeServiceClient is the client API for ChangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChangeServiceClient interface {
	// `levee new`
	CreateChange(ctx context.Context, in *CreateChangeRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee clone`
	CloneChange(ctx context.Context, in *CloneChangeRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee plan`
	PlanChange(ctx context.Context, in *PlanChangeRequest, opts ...grpc.CallOption) (*Plan, error)
	// `levee apply`
	ApplyChange(ctx context.Context, in *ApplyChangeRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	// `levee pause`
	PauseChange(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee resume`
	ResumeChange(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee pause-all`
	PauseAll(ctx context.Context, in *PauseAllRequest, opts ...grpc.CallOption) (*PauseAllResponse, error)
	// `levee resume-all`
	ResumeAll(ctx context.Context, in *PauseAllRequest, opts ...grpc.CallOption) (*PauseAllResponse, error)
	// `levee cancel`
	CancelChange(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee retry`
	RetryChange(ctx context.Context, in *RetryRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee retry-host`
	RetryHost(ctx context.Context, in *RetryHostRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee rollback`
	RollbackChange(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	// `levee approve`
	ApproveChange(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee reject`
	RejectChange(ctx context.Context, in *RejectRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee show`
	GetChange(ctx context.Context, in *GetChangeRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee list`
	ListChanges(ctx context.Context, in *ListChangesRequest, opts ...grpc.CallOption) (*ListChangesResponse, error)
	// `levee archive`
	ArchiveChange(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*Change, error)
	// `levee logs`
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
	// `levee diff`
	GetDiff(ctx context.Context, in *GetDiffRequest, opts ...grpc.CallOption) (*GetDiffResponse, error)
	// `levee trace`
	GetTrace(ctx context.Context, in *GetTraceRequest, opts ...grpc.CallOption) (*GetTraceResponse, error)
	// Real-time status push.
	WatchChange(ctx context.Context, in *WatchChangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error)
	// Real-time log stream.
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
}

type changeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChangeServiceClient(cc grpc.ClientConnInterface) ChangeServiceClient {
	return &changeServiceClient{cc}
}

func (c *changeServiceClient) CreateChange(ctx context.Context, in *CreateChangeRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_CreateChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) CloneChange(ctx context.Context, in *CloneChangeRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_CloneChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) PlanChange(ctx context.Context, in *PlanChangeRequest, opts ...grpc.CallOption) (*Plan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Plan)
	err := c.cc.Invoke(ctx, ChangeService_PlanChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) ApplyChange(ctx context.Context, in *ApplyChangeRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, ChangeService_ApplyChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) PauseChange(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_PauseChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) ResumeChange(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_ResumeChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) PauseAll(ctx context.Context, in *PauseAllRequest, opts ...grpc.CallOption) (*PauseAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseAllResponse)
	err := c.cc.Invoke(ctx, ChangeService_PauseAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) ResumeAll(ctx context.Context, in *PauseAllRequest, opts ...grpc.CallOption) (*PauseAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseAllResponse)
	err := c.cc.Invoke(ctx, ChangeService_ResumeAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) CancelChange(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_CancelChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) RetryChange(ctx context.Context, in *RetryRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_RetryChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) RetryHost(ctx context.Context, in *RetryHostRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_RetryHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) RollbackChange(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, ChangeService_RollbackChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) ApproveChange(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_ApproveChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) RejectChange(ctx context.Context, in *RejectRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_RejectChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) GetChange(ctx context.Context, in *GetChangeRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_GetChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) ListChanges(ctx context.Context, in *ListChangesRequest, opts ...grpc.CallOption) (*ListChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChangesResponse)
	err := c.cc.Invoke(ctx, ChangeService_ListChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) ArchiveChange(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, ChangeService_ArchiveChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, ChangeService_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) GetDiff(ctx context.Context, in *GetDiffRequest, opts ...grpc.CallOption) (*GetDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiffResponse)
	err := c.cc.Invoke(ctx, ChangeService_GetDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) GetTrace(ctx context.Context, in *GetTraceRequest, opts ...grpc.CallOption) (*GetTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTraceResponse)
	err := c.cc.Invoke(ctx, ChangeService_GetTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeServiceClient) WatchChange(ctx context.Context, in *WatchChangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeService_ServiceDesc.Streams[0], ChangeService_WatchChange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchChangeRequest, ChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeService_WatchChangeClient = grpc.ServerStreamingClient[ChangeEvent]

func (c *changeServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeService_ServiceDesc.Streams[1], ChangeService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeService_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

// ChangeServiceServer is the server API for ChangeService service.
// All implementations must embed UnimplementedChangeServiceServer
// for forward compatibility.
type ChangeServiceServer interface {
	// `levee new`
	CreateChange(context.Context, *CreateChangeRequest) (*Change, error)
	// `levee clone`
	CloneChange(context.Context, *CloneChangeRequest) (*Change, error)
	// `levee plan`
	PlanChange(context.Context, *PlanChangeRequest) (*Plan, error)
	// `levee apply`
	ApplyChange(context.Context, *ApplyChangeRequest) (*ApplyResponse, error)
	// `levee pause`
	PauseChange(context.Context, *PauseRequest) (*Change, error)
	// `levee resume`
	ResumeChange(context.Context, *PauseRequest) (*Change, error)
	// `levee pause-all`
	PauseAll(context.Context, *PauseAllRequest) (*PauseAllResponse, error)
	// `levee resume-all`
	ResumeAll(context.Context, *PauseAllRequest) (*PauseAllResponse, error)
	// `levee cancel`
	CancelChange(context.Context, *CancelRequest) (*Change, error)
	// `levee retry`
	RetryChange(context.Context, *RetryRequest) (*Change, error)
	// `levee retry-host`
	RetryHost(context.Context, *RetryHostRequest) (*Change, error)
	// `levee rollback`
	RollbackChange(context.Context, *RollbackRequest) (*RollbackResponse, error)
	// `levee approve`
	ApproveChange(context.Context, *ApproveRequest) (*Change, error)
	// `levee reject`
	RejectChange(context.Context, *RejectRequest) (*Change, error)
	// `levee show`
	GetChange(context.Context, *GetChangeRequest) (*Change, error)
	// `levee list`
	ListChanges(context.Context, *ListChangesRequest) (*ListChangesResponse, error)
	// `levee archive`
	ArchiveChange(context.Context, *ArchiveRequest) (*Change, error)
	// `levee logs`
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
	// `levee diff`
	GetDiff(context.Context, *GetDiffRequest) (*GetDiffResponse, error)
	// `levee trace`
	GetTrace(context.Context, *GetTraceRequest) (*GetTraceResponse, error)
	// Real-time status push.
	WatchChange(*WatchChangeRequest, grpc.ServerStreamingServer[ChangeEvent]) error
	// Real-time log stream.
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	mustEmbedUnimplementedChangeServiceServer()
}

// UnimplementedChangeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChangeServiceServer struct{}

func (UnimplementedChangeServiceServer) CreateChange(context.Context, *CreateChangeRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChange not implemented")
}
func (UnimplementedChangeServiceServer) CloneChange(context.Context, *CloneChangeRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method CloneChange not implemented")
}
func (UnimplementedChangeServiceServer) PlanChange(context.Context, *PlanChangeRequest) (*Plan, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanChange not implemented")
}
func (UnimplementedChangeServiceServer) ApplyChange(context.Context, *ApplyChangeRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyChange not implemented")
}
func (UnimplementedChangeServiceServer) PauseChange(context.Context, *PauseRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseChange not implemented")
}
func (UnimplementedChangeServiceServer) ResumeChange(context.Context, *PauseRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeChange not implemented")
}
func (UnimplementedChangeServiceServer) PauseAll(context.Context, *PauseAllRequest) (*PauseAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseAll not implemented")
}
func (UnimplementedChangeServiceServer) ResumeAll(context.Context, *PauseAllRequest) (*PauseAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeAll not implemented")
}
func (UnimplementedChangeServiceServer) CancelChange(context.Context, *CancelRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelChange not implemented")
}
func (UnimplementedChangeServiceServer) RetryChange(context.Context, *RetryRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryChange not implemented")
}
func (UnimplementedChangeServiceServer) RetryHost(context.Context, *RetryHostRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryHost not implemented")
}
func (UnimplementedChangeServiceServer) RollbackChange(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackChange not implemented")
}
func (UnimplementedChangeServiceServer) ApproveChange(context.Context, *ApproveRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveChange not implemented")
}
func (UnimplementedChangeServiceServer) RejectChange(context.Context, *RejectRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectChange not implemented")
}
func (UnimplementedChangeServiceServer) GetChange(context.Context, *GetChangeRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChange not implemented")
}
func (UnimplementedChangeServiceServer) ListChanges(context.Context, *ListChangesRequest) (*ListChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChanges not implemented")
}
func (UnimplementedChangeServiceServer) ArchiveChange(context.Context, *ArchiveRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveChange not implemented")
}
func (UnimplementedChangeServiceServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedChangeServiceServer) GetDiff(context.Context, *GetDiffRequest) (*GetDiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiff not implemented")
}
func (UnimplementedChangeServiceServer) GetTrace(context.Context, *GetTraceRequest) (*GetTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrace not implemented")
}
func (UnimplementedChangeServiceServer) WatchChange(*WatchChangeRequest, grpc.ServerStreamingServer[ChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchChange not implemented")
}
func (UnimplementedChangeServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedChangeServiceServer) mustEmbedUnimplementedChangeServiceServer() {}
func (UnimplementedChangeServiceServer) testEmbeddedByValue()                       {}

// UnsafeChangeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangeServiceServer will
// result in compilation errors.
type UnsafeChangeServiceServer interface {
	mustEmbedUnimplementedChangeServiceServer()
}

func RegisterChangeServiceServer(s grpc.ServiceRegistrar, srv ChangeServiceServer) {
	// If the following call panics, it indicates UnimplementedChangeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChangeService_ServiceDesc, srv)
}

func _ChangeService_CreateChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).CreateChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_CreateChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).CreateChange(ctx, req.(*CreateChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_CloneChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).CloneChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_CloneChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).CloneChange(ctx, req.(*CloneChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_PlanChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).PlanChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_PlanChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).PlanChange(ctx, req.(*PlanChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_ApplyChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).ApplyChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_ApplyChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).ApplyChange(ctx, req.(*ApplyChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_PauseChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).PauseChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_PauseChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).PauseChange(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_ResumeChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).ResumeChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_ResumeChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).ResumeChange(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_PauseAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).PauseAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_PauseAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).PauseAll(ctx, req.(*PauseAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_ResumeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).ResumeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_ResumeAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).ResumeAll(ctx, req.(*PauseAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_CancelChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).CancelChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_CancelChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).CancelChange(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_RetryChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).RetryChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_RetryChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).RetryChange(ctx, req.(*RetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_RetryHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).RetryHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_RetryHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).RetryHost(ctx, req.(*RetryHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_RollbackChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).RollbackChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_RollbackChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).RollbackChange(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_ApproveChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).ApproveChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_ApproveChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).ApproveChange(ctx, req.(*ApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_RejectChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).RejectChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_RejectChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).RejectChange(ctx, req.(*RejectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_GetChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).GetChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_GetChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).GetChange(ctx, req.(*GetChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_ListChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).ListChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_ListChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).ListChanges(ctx, req.(*ListChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_ArchiveChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).ArchiveChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_ArchiveChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).ArchiveChange(ctx, req.(*ArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_GetDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).GetDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_GetDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).GetDiff(ctx, req.(*GetDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_GetTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeServiceServer).GetTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeService_GetTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeServiceServer).GetTrace(ctx, req.(*GetTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeService_WatchChange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchChangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeServiceServer).WatchChange(m, &grpc.GenericServerStream[WatchChangeRequest, ChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeService_WatchChangeServer = grpc.ServerStreamingServer[ChangeEvent]

func _ChangeService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeService_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

// ChangeService_ServiceDesc is the grpc.ServiceDesc for ChangeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levee.ChangeService",
	HandlerType: (*ChangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChange",
			Handler:    _ChangeService_CreateChange_Handler,
		},
		{
			MethodName: "CloneChange",
			Handler:    _ChangeService_CloneChange_Handler,
		},
		{
			MethodName: "PlanChange",
			Handler:    _ChangeService_PlanChange_Handler,
		},
		{
			MethodName: "ApplyChange",
			Handler:    _ChangeService_ApplyChange_Handler,
		},
		{
			MethodName: "PauseChange",
			Handler:    _ChangeService_PauseChange_Handler,
		},
		{
			MethodName: "ResumeChange",
			Handler:    _ChangeService_ResumeChange_Handler,
		},
		{
			MethodName: "PauseAll",
			Handler:    _ChangeService_PauseAll_Handler,
		},
		{
			MethodName: "ResumeAll",
			Handler:    _ChangeService_ResumeAll_Handler,
		},
		{
			MethodName: "CancelChange",
			Handler:    _ChangeService_CancelChange_Handler,
		},
		{
			MethodName: "RetryChange",
			Handler:    _ChangeService_RetryChange_Handler,
		},
		{
			MethodName: "RetryHost",
			Handler:    _ChangeService_RetryHost_Handler,
		},
		{
			MethodName: "RollbackChange",
			Handler:    _ChangeService_RollbackChange_Handler,
		},
		{
			MethodName: "ApproveChange",
			Handler:    _ChangeService_ApproveChange_Handler,
		},
		{
			MethodName: "RejectChange",
			Handler:    _ChangeService_RejectChange_Handler,
		},
		{
			MethodName: "GetChange",
			Handler:    _ChangeService_GetChange_Handler,
		},
		{
			MethodName: "ListChanges",
			Handler:    _ChangeService_ListChanges_Handler,
		},
		{
			MethodName: "ArchiveChange",
			Handler:    _ChangeService_ArchiveChange_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _ChangeService_GetLogs_Handler,
		},
		{
			MethodName: "GetDiff",
			Handler:    _ChangeService_GetDiff_Handler,
		},
		{
			MethodName: "GetTrace",
			Handler:    _ChangeService_GetTrace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchChange",
			Handler:       _ChangeService_WatchChange_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _ChangeService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "levee.proto",
}

const (
	TemplateService_CreateTemplate_FullMethodName      = "/levee.TemplateService/CreateTemplate"
	TemplateService_GetTemplate_FullMethodName         = "/levee.TemplateService/GetTemplate"
	TemplateService_ListTemplates_FullMethodName       = "/levee.TemplateService/ListTemplates"
	TemplateService_DeleteTemplate_FullMethodName      = "/levee.TemplateService/DeleteTemplate"
	TemplateService_InstantiateTemplate_FullMethodName = "/levee.TemplateService/InstantiateTemplate"
)

// TemplateServiceClient is the client API for TemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateServiceClient interface {
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*Template, error)
	GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*Template, error)
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	InstantiateTemplate(ctx context.Context, in *InstantiateTemplateRequest, opts ...grpc.CallOption) (*Change, error)
}

type templateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateServiceClient(cc grpc.ClientConnInterface) TemplateServiceClient {
	return &templateServiceClient{cc}
}

func (c *templateServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Template)
	err := c.cc.Invoke(ctx, TemplateService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Template)
	err := c.cc.Invoke(ctx, TemplateService_GetTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, TemplateService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TemplateService_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) InstantiateTemplate(ctx context.Context, in *InstantiateTemplateRequest, opts ...grpc.CallOption) (*Change, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Change)
	err := c.cc.Invoke(ctx, TemplateService_InstantiateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServiceServer is the server API for TemplateService service.
// All implementations must embed UnimplementedTemplateServiceServer
// for forward compatibility.
type TemplateServiceServer interface {
	CreateTemplate(context.Context, *CreateTemplateRequest) (*Template, error)
	GetTemplate(context.Context, *GetTemplateRequest) (*Template, error)
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*emptypb.Empty, error)
	InstantiateTemplate(context.Context, *InstantiateTemplateRequest) (*Change, error)
	mustEmbedUnimplementedTemplateServiceServer()
}

// UnimplementedTemplateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemplateServiceServer struct{}

func (UnimplementedTemplateServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*Template, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedTemplateServiceServer) GetTemplate(context.Context, *GetTemplateRequest) (*Template, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedTemplateServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedTemplateServiceServer) DeleteTemplate(context.Context, *DeleteTemplateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedTemplateServiceServer) InstantiateTemplate(context.Context, *InstantiateTemplateRequest) (*Change, error) {
	return nil, status.Error(codes.Unimplemented, "method InstantiateTemplate not implemented")
}
func (UnimplementedTemplateServiceServer) mustEmbedUnimplementedTemplateServiceServer() {}
func (UnimplementedTemplateServiceServer) testEmbeddedByValue()                         {}

// UnsafeTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateServiceServer will
// result in compilation errors.
type UnsafeTemplateServiceServer interface {
	mustEmbedUnimplementedTemplateServiceServer()
}

func RegisterTemplateServiceServer(s grpc.ServiceRegistrar, srv TemplateServiceServer) {
	// If the following call panics, it indicates UnimplementedTemplateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemplateService_ServiceDesc, srv)
}

func _TemplateService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_GetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).GetTemplate(ctx, req.(*GetTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_InstantiateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstantiateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).InstantiateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_InstantiateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).InstantiateTemplate(ctx, req.(*InstantiateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemplateService_ServiceDesc is the grpc.ServiceDesc for TemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levee.TemplateService",
	HandlerType: (*TemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplate",
			Handler:    _TemplateService_CreateTemplate_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _TemplateService_GetTemplate_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _TemplateService_ListTemplates_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _TemplateService_DeleteTemplate_Handler,
		},
		{
			MethodName: "InstantiateTemplate",
			Handler:    _TemplateService_InstantiateTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "levee.proto",
}

const (
	TargetService_AddTarget_FullMethodName    = "/levee.TargetService/AddTarget"
	TargetService_RemoveTarget_FullMethodName = "/levee.TargetService/RemoveTarget"
	TargetService_ListTargets_FullMethodName  = "/levee.TargetService/ListTargets"
	TargetService_GetTarget_FullMethodName    = "/levee.TargetService/GetTarget"
	TargetService_CheckTarget_FullMethodName  = "/levee.TargetService/CheckTarget"
)

// TargetServiceClient is the client API for TargetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TargetServiceClient interface {
	AddTarget(ctx context.Context, in *AddTargetRequest, opts ...grpc.CallOption) (*Target, error)
	RemoveTarget(ctx context.Context, in *RemoveTargetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListTargets(ctx context.Context, in *ListTargetsRequest, opts ...grpc.CallOption) (*ListTargetsResponse, error)
	GetTarget(ctx context.Context, in *GetTargetRequest, opts ...grpc.CallOption) (*Target, error)
	CheckTarget(ctx context.Context, in *CheckTargetRequest, opts ...grpc.CallOption) (*CheckTargetResponse, error)
}

type targetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTargetServiceClient(cc grpc.ClientConnInterface) TargetServiceClient {
	return &targetServiceClient{cc}
}

func (c *targetServiceClient) AddTarget(ctx context.Context, in *AddTargetRequest, opts ...grpc.CallOption) (*Target, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Target)
	err := c.cc.Invoke(ctx, TargetService_AddTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetServiceClient) RemoveTarget(ctx context.Context, in *RemoveTargetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetService_RemoveTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetServiceClient) ListTargets(ctx context.Context, in *ListTargetsRequest, opts ...grpc.CallOption) (*ListTargetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTargetsResponse)
	err := c.cc.Invoke(ctx, TargetService_ListTargets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetServiceClient) GetTarget(ctx context.Context, in *GetTargetRequest, opts ...grpc.CallOption) (*Target, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Target)
	err := c.cc.Invoke(ctx, TargetService_GetTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetServiceClient) CheckTarget(ctx context.Context, in *CheckTargetRequest, opts ...grpc.CallOption) (*CheckTargetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTargetResponse)
	err := c.cc.Invoke(ctx, TargetService_CheckTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetServiceServer is the server API for TargetService service.
// All implementations must embed UnimplementedTargetServiceServer
// for forward compatibility.
type TargetServiceServer interface {
	AddTarget(context.Context, *AddTargetRequest) (*Target, error)
	RemoveTarget(context.Context, *RemoveTargetRequest) (*emptypb.Empty, error)
	ListTargets(context.Context, *ListTargetsRequest) (*ListTargetsResponse, error)
	GetTarget(context.Context, *GetTargetRequest) (*Target, error)
	CheckTarget(context.Context, *CheckTargetRequest) (*CheckTargetResponse, error)
	mustEmbedUnimplementedTargetServiceServer()
}

// UnimplementedTargetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTargetServiceServer struct{}

func (UnimplementedTargetServiceServer) AddTarget(context.Context, *AddTargetRequest) (*Target, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTarget not implemented")
}
func (UnimplementedTargetServiceServer) RemoveTarget(context.Context, *RemoveTargetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTarget not implemented")
}
func (UnimplementedTargetServiceServer) ListTargets(context.Context, *ListTargetsRequest) (*ListTargetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTargets not implemented")
}
func (UnimplementedTargetServiceServer) GetTarget(context.Context, *GetTargetRequest) (*Target, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTarget not implemented")
}
func (UnimplementedTargetServiceServer) CheckTarget(context.Context, *CheckTargetRequest) (*CheckTargetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTarget not implemented")
}
func (UnimplementedTargetServiceServer) mustEmbedUnimplementedTargetServiceServer() {}
func (UnimplementedTargetServiceServer) testEmbeddedByValue()                       {}

// UnsafeTargetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TargetServiceServer will
// result in compilation errors.
type UnsafeTargetServiceServer interface {
	mustEmbedUnimplementedTargetServiceServer()
}

func RegisterTargetServiceServer(s grpc.ServiceRegistrar, srv TargetServiceServer) {
	// If the following call panics, it indicates UnimplementedTargetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TargetService_ServiceDesc, srv)
}

func _TargetService_AddTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServiceServer).AddTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetService_AddTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServiceServer).AddTarget(ctx, req.(*AddTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetService_RemoveTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServiceServer).RemoveTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetService_RemoveTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServiceServer).RemoveTarget(ctx, req.(*RemoveTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetService_ListTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServiceServer).ListTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetService_ListTargets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServiceServer).ListTargets(ctx, req.(*ListTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetService_GetTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServiceServer).GetTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetService_GetTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServiceServer).GetTarget(ctx, req.(*GetTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetService_CheckTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServiceServer).CheckTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetService_CheckTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServiceServer).CheckTarget(ctx, req.(*CheckTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TargetService_ServiceDesc is the grpc.ServiceDesc for TargetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TargetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levee.TargetService",
	HandlerType: (*TargetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTarget",
			Handler:    _TargetService_AddTarget_Handler,
		},
		{
			MethodName: "RemoveTarget",
			Handler:    _TargetService_RemoveTarget_Handler,
		},
		{
			MethodName: "ListTargets",
			Handler:    _TargetService_ListTargets_Handler,
		},
		{
			MethodName: "GetTarget",
			Handler:    _TargetService_GetTarget_Handler,
		},
		{
			MethodName: "CheckTarget",
			Handler:    _TargetService_CheckTarget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "levee.proto",
}

const (
	AuditService_GetAuditLog_FullMethodName     = "/levee.AuditService/GetAuditLog"
	AuditService_ListAuditTraces_FullMethodName = "/levee.AuditService/ListAuditTraces"
	AuditService_VerifyHashChain_FullMethodName = "/levee.AuditService/VerifyHashChain"
	AuditService_GetRunReport_FullMethodName    = "/levee.AuditService/GetRunReport"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*GetAuditLogResponse, error)
	ListAuditTraces(ctx context.Context, in *ListAuditTracesRequest, opts ...grpc.CallOption) (*ListAuditTracesResponse, error)
	VerifyHashChain(ctx context.Context, in *VerifyHashChainRequest, opts ...grpc.CallOption) (*VerifyHashChainResponse, error)
	GetRunReport(ctx context.Context, in *GetRunReportRequest, opts ...grpc.CallOption) (*RunReport, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*GetAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditLogResponse)
	err := c.cc.Invoke(ctx, AuditService_GetAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListAuditTraces(ctx context.Context, in *ListAuditTracesRequest, opts ...grpc.CallOption) (*ListAuditTracesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditTracesResponse)
	err := c.cc.Invoke(ctx, AuditService_ListAuditTraces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) VerifyHashChain(ctx context.Context, in *VerifyHashChainRequest, opts ...grpc.CallOption) (*VerifyHashChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyHashChainResponse)
	err := c.cc.Invoke(ctx, AuditService_VerifyHashChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetRunReport(ctx context.Context, in *GetRunReportRequest, opts ...grpc.CallOption) (*RunReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunReport)
	err := c.cc.Invoke(ctx, AuditService_GetRunReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
type AuditServiceServer interface {
	GetAuditLog(context.Context, *GetAuditLogRequest) (*GetAuditLogResponse, error)
	ListAuditTraces(context.Context, *ListAuditTracesRequest) (*ListAuditTracesResponse, error)
	VerifyHashChain(context.Context, *VerifyHashChainRequest) (*VerifyHashChainResponse, error)
	GetRunReport(context.Context, *GetRunReportRequest) (*RunReport, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) GetAuditLog(context.Context, *GetAuditLogRequest) (*GetAuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditLog not implemented")
}
func (UnimplementedAuditServiceServer) ListAuditTraces(context.Context, *ListAuditTracesRequest) (*ListAuditTracesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditTraces not implemented")
}
func (UnimplementedAuditServiceServer) VerifyHashChain(context.Context, *VerifyHashChainRequest) (*VerifyHashChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyHashChain not implemented")
}
func (UnimplementedAuditServiceServer) GetRunReport(context.Context, *GetRunReportRequest) (*RunReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunReport not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_GetAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetAuditLog(ctx, req.(*GetAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListAuditTraces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditTracesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAuditTraces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAuditTraces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAuditTraces(ctx, req.(*ListAuditTracesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_VerifyHashChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyHashChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).VerifyHashChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_VerifyHashChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).VerifyHashChain(ctx, req.(*VerifyHashChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetRunReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetRunReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetRunReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetRunReport(ctx, req.(*GetRunReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levee.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuditLog",
			Handler:    _AuditService_GetAuditLog_Handler,
		},
		{
			MethodName: "ListAuditTraces",
			Handler:    _AuditService_ListAuditTraces_Handler,
		},
		{
			MethodName: "VerifyHashChain",
			Handler:    _AuditService_VerifyHashChain_Handler,
		},
		{
			MethodName: "GetRunReport",
			Handler:    _AuditService_GetRunReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "levee.proto",
}

const (
	SystemService_GetVersion_FullMethodName = "/levee.SystemService/GetVersion"
	SystemService_GetStatus_FullMethodName  = "/levee.SystemService/GetStatus"
	SystemService_GetConfig_FullMethodName  = "/levee.SystemService/GetConfig"
	SystemService_RunDoctor_FullMethodName  = "/levee.SystemService/RunDoctor"
)

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemServiceClient interface {
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionInfo, error)
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SystemStatus, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Config, error)
	RunDoctor(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DoctorReport, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionInfo)
	err := c.cc.Invoke(ctx, SystemService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SystemStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatus)
	err := c.cc.Invoke(ctx, SystemService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Config, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Config)
	err := c.cc.Invoke(ctx, SystemService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) RunDoctor(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DoctorReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoctorReport)
	err := c.cc.Invoke(ctx, SystemService_RunDoctor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility.
type SystemServiceServer interface {
	GetVersion(context.Context, *emptypb.Empty) (*VersionInfo, error)
	GetStatus(context.Context, *emptypb.Empty) (*SystemStatus, error)
	GetConfig(context.Context, *GetConfigRequest) (*Config, error)
	RunDoctor(context.Context, *emptypb.Empty) (*DoctorReport, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemServiceServer struct{}

func (UnimplementedSystemServiceServer) GetVersion(context.Context, *emptypb.Empty) (*VersionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedSystemServiceServer) GetStatus(context.Context, *emptypb.Empty) (*SystemStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSystemServiceServer) GetConfig(context.Context, *GetConfigRequest) (*Config, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedSystemServiceServer) RunDoctor(context.Context, *emptypb.Empty) (*DoctorReport, error) {
	return nil, status.Error(codes.Unimplemented, "method RunDoctor not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}
func (UnimplementedSystemServiceServer) testEmbeddedByValue()                       {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_RunDoctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).RunDoctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_RunDoctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).RunDoctor(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levee.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _SystemService_GetVersion_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _SystemService_GetStatus_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _SystemService_GetConfig_Handler,
		},
		{
			MethodName: "RunDoctor",
			Handler:    _SystemService_RunDoctor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "levee.proto",
}
