//go:build proto_regenerate

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.0
// source: levee_extra.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertMessage is the wire representation of an alert. Named "AlertMessage"
// to avoid clashing with the alert.Alert domain type when the Go bindings
// are regenerated.
type AlertMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// info/warning/critical
	Severity    string            `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Target      string            `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Title       string            `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Labels      map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fingerprint string            `protobuf:"bytes,8,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// Unix timestamp (seconds since epoch).
	StartsAt int64 `protobuf:"varint,9,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	// Unix timestamp; zero means still firing.
	EndsAt int64 `protobuf:"varint,10,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	// firing/resolved
	Status        string `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertMessage) Reset() {
	*x = AlertMessage{}
	mi := &file_levee_extra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertMessage) ProtoMessage() {}

func (x *AlertMessage) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertMessage.ProtoReflect.Descriptor instead.
func (*AlertMessage) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{0}
}

func (x *AlertMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AlertMessage) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AlertMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlertMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlertMessage) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AlertMessage) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *AlertMessage) GetStartsAt() int64 {
	if x != nil {
		return x.StartsAt
	}
	return 0
}

func (x *AlertMessage) GetEndsAt() int64 {
	if x != nil {
		return x.EndsAt
	}
	return 0
}

func (x *AlertMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AlertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted/duplicate/silenced/invalid/error
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertResponse) Reset() {
	*x = AlertResponse{}
	mi := &file_levee_extra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertResponse) ProtoMessage() {}

func (x *AlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertResponse.ProtoReflect.Descriptor instead.
func (*AlertResponse) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{1}
}

func (x *AlertResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AlertResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetAlertStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertStatusRequest) Reset() {
	*x = GetAlertStatusRequest{}
	mi := &file_levee_extra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertStatusRequest) ProtoMessage() {}

func (x *GetAlertStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAlertStatusRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlertStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AlertStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartsAt      int64                  `protobuf:"varint,3,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt        int64                  `protobuf:"varint,4,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertStatus) Reset() {
	*x = AlertStatus{}
	mi := &file_levee_extra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertStatus) ProtoMessage() {}

func (x *AlertStatus) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertStatus.ProtoReflect.Descriptor instead.
func (*AlertStatus) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{3}
}

func (x *AlertStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AlertStatus) GetStartsAt() int64 {
	if x != nil {
		return x.StartsAt
	}
	return 0
}

func (x *AlertStatus) GetEndsAt() int64 {
	if x != nil {
		return x.EndsAt
	}
	return 0
}

func (x *AlertStatus) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional severity filter; empty means all severities.
	Severity string `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	// Optional source filter; empty means all sources.
	Source        string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_levee_extra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *SubscribeRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type DiagnoseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target host to diagnose.
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// Optional alert id that triggered the diagnosis.
	AlertId string `protobuf:"bytes,2,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	// Optional timeout in seconds; zero means use engine default.
	TimeoutSeconds int64 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiagnoseRequest) Reset() {
	*x = DiagnoseRequest{}
	mi := &file_levee_extra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnoseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnoseRequest) ProtoMessage() {}

func (x *DiagnoseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnoseRequest.ProtoReflect.Descriptor instead.
func (*DiagnoseRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{5}
}

func (x *DiagnoseRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DiagnoseRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *DiagnoseRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type GetDiagnosisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosisRequest) Reset() {
	*x = GetDiagnosisRequest{}
	mi := &file_levee_extra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosisRequest) ProtoMessage() {}

func (x *GetDiagnosisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosisRequest.ProtoReflect.Descriptor instead.
func (*GetDiagnosisRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{6}
}

func (x *GetDiagnosisRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DiagnosticReportMessage is the wire representation of a diagnosis
// report. Named to avoid clashing with diagnosis.DiagnosticReport.
type DiagnosticReportMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Target string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// manual/alert/scheduled
	Trigger string `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	AlertId string `protobuf:"bytes,4,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	// healthy/degraded/unhealthy/unknown
	Status          string            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RootCause       string            `protobuf:"bytes,6,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	Confidence      float64           `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Summary         string            `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	Recommendations []string          `protobuf:"bytes,9,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Errors          []string          `protobuf:"bytes,10,rep,name=errors,proto3" json:"errors,omitempty"`
	StartedAt       int64             `protobuf:"varint,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	DurationMs      int64             `protobuf:"varint,12,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Findings        []*FindingMessage `protobuf:"bytes,13,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiagnosticReportMessage) Reset() {
	*x = DiagnosticReportMessage{}
	mi := &file_levee_extra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticReportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticReportMessage) ProtoMessage() {}

func (x *DiagnosticReportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticReportMessage.ProtoReflect.Descriptor instead.
func (*DiagnosticReportMessage) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{7}
}

func (x *DiagnosticReportMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiagnosticReportMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DiagnosticReportMessage) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *DiagnosticReportMessage) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *DiagnosticReportMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DiagnosticReportMessage) GetRootCause() string {
	if x != nil {
		return x.RootCause
	}
	return ""
}

func (x *DiagnosticReportMessage) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DiagnosticReportMessage) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DiagnosticReportMessage) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *DiagnosticReportMessage) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *DiagnosticReportMessage) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *DiagnosticReportMessage) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *DiagnosticReportMessage) GetFindings() []*FindingMessage {
	if x != nil {
		return x.Findings
	}
	return nil
}

type FindingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Evidence      string                 `protobuf:"bytes,6,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Suggestion    string                 `protobuf:"bytes,7,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingMessage) Reset() {
	*x = FindingMessage{}
	mi := &file_levee_extra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingMessage) ProtoMessage() {}

func (x *FindingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingMessage.ProtoReflect.Descriptor instead.
func (*FindingMessage) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{8}
}

func (x *FindingMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FindingMessage) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FindingMessage) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *FindingMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindingMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FindingMessage) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *FindingMessage) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_levee_extra_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ReplyMessage is the wire representation of conversation.Reply.
type ReplyMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Optional action type: approve/reject/execute/modify/cancel/none.
	ActionType string `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	// Optional action payload.
	ActionPayload map[string]string `protobuf:"bytes,3,rep,name=action_payload,json=actionPayload,proto3" json:"action_payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional session id the reply belongs to.
	SessionId     string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_levee_extra_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{10}
}

func (x *ReplyMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReplyMessage) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ReplyMessage) GetActionPayload() map[string]string {
	if x != nil {
		return x.ActionPayload
	}
	return nil
}

func (x *ReplyMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Group is a hierarchical inventory group. Names are unique and path-style.
type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_levee_extra_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{11}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_levee_extra_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{12}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_levee_extra_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{13}
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_levee_extra_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{14}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_levee_extra_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_levee_extra_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{16}
}

// ImportTargetsRequest carries the raw YAML content of an inventory file.
type ImportTargetsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	YamlContent string                 `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	// DefaultGroup optionally assigns every imported target lacking an
	// explicit group to this group name (created when missing).
	DefaultGroup  string `protobuf:"bytes,2,opt,name=default_group,json=defaultGroup,proto3" json:"default_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportTargetsRequest) Reset() {
	*x = ImportTargetsRequest{}
	mi := &file_levee_extra_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportTargetsRequest) ProtoMessage() {}

func (x *ImportTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportTargetsRequest.ProtoReflect.Descriptor instead.
func (*ImportTargetsRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{17}
}

func (x *ImportTargetsRequest) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

func (x *ImportTargetsRequest) GetDefaultGroup() string {
	if x != nil {
		return x.DefaultGroup
	}
	return ""
}

type ImportTargetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       int32                  `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated       int32                  `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportTargetsResponse) Reset() {
	*x = ImportTargetsResponse{}
	mi := &file_levee_extra_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportTargetsResponse) ProtoMessage() {}

func (x *ImportTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportTargetsResponse.ProtoReflect.Descriptor instead.
func (*ImportTargetsResponse) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{18}
}

func (x *ImportTargetsResponse) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ImportTargetsResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *ImportTargetsResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ImportTargetsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type SetTargetStatusRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TargetId string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Status must be one of active|frozen|retired.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTargetStatusRequest) Reset() {
	*x = SetTargetStatusRequest{}
	mi := &file_levee_extra_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTargetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTargetStatusRequest) ProtoMessage() {}

func (x *SetTargetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTargetStatusRequest.ProtoReflect.Descriptor instead.
func (*SetTargetStatusRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{19}
}

func (x *SetTargetStatusRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SetTargetStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetTargetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTargetStatusResponse) Reset() {
	*x = SetTargetStatusResponse{}
	mi := &file_levee_extra_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTargetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTargetStatusResponse) ProtoMessage() {}

func (x *SetTargetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTargetStatusResponse.ProtoReflect.Descriptor instead.
func (*SetTargetStatusResponse) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{20}
}

func (x *SetTargetStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetTargetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// TargetHistoryEntry is one change run that executed on the queried host.
type TargetHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Creator       string                 `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetHistoryEntry) Reset() {
	*x = TargetHistoryEntry{}
	mi := &file_levee_extra_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetHistoryEntry) ProtoMessage() {}

func (x *TargetHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetHistoryEntry.ProtoReflect.Descriptor instead.
func (*TargetHistoryEntry) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{21}
}

func (x *TargetHistoryEntry) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TargetHistoryEntry) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *TargetHistoryEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TargetHistoryEntry) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *TargetHistoryEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type TargetHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host is the address (targets.hostname) to look up runs for.
	Host          string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Limit         int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetHistoryRequest) Reset() {
	*x = TargetHistoryRequest{}
	mi := &file_levee_extra_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetHistoryRequest) ProtoMessage() {}

func (x *TargetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetHistoryRequest.ProtoReflect.Descriptor instead.
func (*TargetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{22}
}

func (x *TargetHistoryRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TargetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TargetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TargetHistoryEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetHistoryResponse) Reset() {
	*x = TargetHistoryResponse{}
	mi := &file_levee_extra_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetHistoryResponse) ProtoMessage() {}

func (x *TargetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_levee_extra_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetHistoryResponse.ProtoReflect.Descriptor instead.
func (*TargetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_levee_extra_proto_rawDescGZIP(), []int{23}
}

func (x *TargetHistoryResponse) GetEntries() []*TargetHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_levee_extra_proto protoreflect.FileDescriptor

const file_levee_extra_proto_rawDesc = "" +
	"\n" +
	"\x11levee_extra.proto\x12\x05levee\"\x86\x03\n" +
	"\fAlertMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x127\n" +
	"\x06labels\x18\a \x03(\v2\x1f.levee.AlertMessage.LabelsEntryR\x06labels\x12 \n" +
	"\vfingerprint\x18\b \x01(\tR\vfingerprint\x12\x1b\n" +
	"\tstarts_at\x18\t \x01(\x03R\bstartsAt\x12\x17\n" +
	"\aends_at\x18\n" +
	" \x01(\x03R\x06endsAt\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\rAlertResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"'\n" +
	"\x15GetAlertStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x87\x01\n" +
	"\vAlertStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tstarts_at\x18\x03 \x01(\x03R\bstartsAt\x12\x17\n" +
	"\aends_at\x18\x04 \x01(\x03R\x06endsAt\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\"F\n" +
	"\x10SubscribeRequest\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"m\n" +
	"\x0fDiagnoseRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x19\n" +
	"\balert_id\x18\x02 \x01(\tR\aalertId\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x03R\x0etimeoutSeconds\"%\n" +
	"\x13GetDiagnosisRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9c\x03\n" +
	"\x17DiagnosticReportMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\atrigger\x18\x03 \x01(\tR\atrigger\x12\x19\n" +
	"\balert_id\x18\x04 \x01(\tR\aalertId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"root_cause\x18\x06 \x01(\tR\trootCause\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary\x12(\n" +
	"\x0frecommendations\x18\t \x03(\tR\x0frecommendations\x12\x16\n" +
	"\x06errors\x18\n" +
	" \x03(\tR\x06errors\x12\x1d\n" +
	"\n" +
	"started_at\x18\v \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vduration_ms\x18\f \x01(\x03R\n" +
	"durationMs\x121\n" +
	"\bfindings\x18\r \x03(\v2\x15.levee.FindingMessageR\bfindings\"\xcc\x01\n" +
	"\x0eFindingMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bevidence\x18\x06 \x01(\tR\bevidence\x12\x1e\n" +
	"\n" +
	"suggestion\x18\a \x01(\tR\n" +
	"suggestion\"`\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\xf3\x01\n" +
	"\fReplyMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12M\n" +
	"\x0eaction_payload\x18\x03 \x03(\v2&.levee.ReplyMessage.ActionPayloadEntryR\ractionPayload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x1a@\n" +
	"\x12ActionPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\"E\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"\x13\n" +
	"\x11ListGroupsRequest\":\n" +
	"\x12ListGroupsResponse\x12$\n" +
	"\x06groups\x18\x01 \x03(\v2\f.levee.GroupR\x06groups\"$\n" +
	"\x12DeleteGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteGroupResponse\"^\n" +
	"\x14ImportTargetsRequest\x12!\n" +
	"\fyaml_content\x18\x01 \x01(\tR\vyamlContent\x12#\n" +
	"\rdefault_group\x18\x02 \x01(\tR\fdefaultGroup\"{\n" +
	"\x15ImportTargetsResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\x05R\acreated\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\x05R\aupdated\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"M\n" +
	"\x16SetTargetStatusRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"A\n" +
	"\x17SetTargetStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xa1\x01\n" +
	"\x12TargetHistoryEntry\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\acreator\x18\x04 \x01(\tR\acreator\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"@\n" +
	"\x14TargetHistoryRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"L\n" +
	"\x15TargetHistoryResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.levee.TargetHistoryEntryR\aentries2\xd0\x01\n" +
	"\fAlertService\x129\n" +
	"\fReceiveAlert\x12\x13.levee.AlertMessage\x1a\x14.levee.AlertResponse\x12B\n" +
	"\x0eGetAlertStatus\x12\x1c.levee.GetAlertStatusRequest\x1a\x12.levee.AlertStatus\x12A\n" +
	"\x0fSubscribeAlerts\x12\x17.levee.SubscribeRequest\x1a\x13.levee.AlertMessage0\x012\xa2\x01\n" +
	"\x10DiagnosisService\x12B\n" +
	"\bDiagnose\x12\x16.levee.DiagnoseRequest\x1a\x1e.levee.DiagnosticReportMessage\x12J\n" +
	"\fGetDiagnosis\x12\x1a.levee.GetDiagnosisRequest\x1a\x1e.levee.DiagnosticReportMessage2\x9d\x01\n" +
	"\x13ConversationService\x12=\n" +
	"\vSendMessage\x12\x19.levee.SendMessageRequest\x1a\x13.levee.ReplyMessage\x12G\n" +
	"\x15SubscribeConversation\x12\x17.levee.SubscribeRequest\x1a\x13.levee.ReplyMessage0\x012\xbd\x03\n" +
	"\x10InventoryService\x12A\n" +
	"\n" +
	"ListGroups\x12\x18.levee.ListGroupsRequest\x1a\x19.levee.ListGroupsResponse\x126\n" +
	"\vCreateGroup\x12\x19.levee.CreateGroupRequest\x1a\f.levee.Group\x12D\n" +
	"\vDeleteGroup\x12\x19.levee.DeleteGroupRequest\x1a\x1a.levee.DeleteGroupResponse\x12J\n" +
	"\rImportTargets\x12\x1b.levee.ImportTargetsRequest\x1a\x1c.levee.ImportTargetsResponse\x12P\n" +
	"\x0fSetTargetStatus\x12\x1d.levee.SetTargetStatusRequest\x1a\x1e.levee.SetTargetStatusResponse\x12J\n" +
	"\rTargetHistory\x12\x1b.levee.TargetHistoryRequest\x1a\x1c.levee.TargetHistoryResponseB,Z*github.com/nexus/levee/internal/grpc/pb;pbb\x06proto3"

var (
	file_levee_extra_proto_rawDescOnce sync.Once
	file_levee_extra_proto_rawDescData []byte
)

func file_levee_extra_proto_rawDescGZIP() []byte {
	file_levee_extra_proto_rawDescOnce.Do(func() {
		file_levee_extra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_levee_extra_proto_rawDesc), len(file_levee_extra_proto_rawDesc)))
	})
	return file_levee_extra_proto_rawDescData
}

var file_levee_extra_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_levee_extra_proto_goTypes = []any{
	(*AlertMessage)(nil),            // 0: levee.AlertMessage
	(*AlertResponse)(nil),           // 1: levee.AlertResponse
	(*GetAlertStatusRequest)(nil),   // 2: levee.GetAlertStatusRequest
	(*AlertStatus)(nil),             // 3: levee.AlertStatus
	(*SubscribeRequest)(nil),        // 4: levee.SubscribeRequest
	(*DiagnoseRequest)(nil),         // 5: levee.DiagnoseRequest
	(*GetDiagnosisRequest)(nil),     // 6: levee.GetDiagnosisRequest
	(*DiagnosticReportMessage)(nil), // 7: levee.DiagnosticReportMessage
	(*FindingMessage)(nil),          // 8: levee.FindingMessage
	(*SendMessageRequest)(nil),      // 9: levee.SendMessageRequest
	(*ReplyMessage)(nil),            // 10: levee.ReplyMessage
	(*Group)(nil),                   // 11: levee.Group
	(*CreateGroupRequest)(nil),      // 12: levee.CreateGroupRequest
	(*ListGroupsRequest)(nil),       // 13: levee.ListGroupsRequest
	(*ListGroupsResponse)(nil),      // 14: levee.ListGroupsResponse
	(*DeleteGroupRequest)(nil),      // 15: levee.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),     // 16: levee.DeleteGroupResponse
	(*ImportTargetsRequest)(nil),    // 17: levee.ImportTargetsRequest
	(*ImportTargetsResponse)(nil),   // 18: levee.ImportTargetsResponse
	(*SetTargetStatusRequest)(nil),  // 19: levee.SetTargetStatusRequest
	(*SetTargetStatusResponse)(nil), // 20: levee.SetTargetStatusResponse
	(*TargetHistoryEntry)(nil),      // 21: levee.TargetHistoryEntry
	(*TargetHistoryRequest)(nil),    // 22: levee.TargetHistoryRequest
	(*TargetHistoryResponse)(nil),   // 23: levee.TargetHistoryResponse
	nil,                             // 24: levee.AlertMessage.LabelsEntry
	nil,                             // 25: levee.ReplyMessage.ActionPayloadEntry
}
var file_levee_extra_proto_depIdxs = []int32{
	24, // 0: levee.AlertMessage.labels:type_name -> levee.AlertMessage.LabelsEntry
	8,  // 1: levee.DiagnosticReportMessage.findings:type_name -> levee.FindingMessage
	25, // 2: levee.ReplyMessage.action_payload:type_name -> levee.ReplyMessage.ActionPayloadEntry
	11, // 3: levee.ListGroupsResponse.groups:type_name -> levee.Group
	21, // 4: levee.TargetHistoryResponse.entries:type_name -> levee.TargetHistoryEntry
	0,  // 5: levee.AlertService.ReceiveAlert:input_type -> levee.AlertMessage
	2,  // 6: levee.AlertService.GetAlertStatus:input_type -> levee.GetAlertStatusRequest
	4,  // 7: levee.AlertService.SubscribeAlerts:input_type -> levee.SubscribeRequest
	5,  // 8: levee.DiagnosisService.Diagnose:input_type -> levee.DiagnoseRequest
	6,  // 9: levee.DiagnosisService.GetDiagnosis:input_type -> levee.GetDiagnosisRequest
	9,  // 10: levee.ConversationService.SendMessage:input_type -> levee.SendMessageRequest
	4,  // 11: levee.ConversationService.SubscribeConversation:input_type -> levee.SubscribeRequest
	13, // 12: levee.InventoryService.ListGroups:input_type -> levee.ListGroupsRequest
	12, // 13: levee.InventoryService.CreateGroup:input_type -> levee.CreateGroupRequest
	15, // 14: levee.InventoryService.DeleteGroup:input_type -> levee.DeleteGroupRequest
	17, // 15: levee.InventoryService.ImportTargets:input_type -> levee.ImportTargetsRequest
	19, // 16: levee.InventoryService.SetTargetStatus:input_type -> levee.SetTargetStatusRequest
	22, // 17: levee.InventoryService.TargetHistory:input_type -> levee.TargetHistoryRequest
	1,  // 18: levee.AlertService.ReceiveAlert:output_type -> levee.AlertResponse
	3,  // 19: levee.AlertService.GetAlertStatus:output_type -> levee.AlertStatus
	0,  // 20: levee.AlertService.SubscribeAlerts:output_type -> levee.AlertMessage
	7,  // 21: levee.DiagnosisService.Diagnose:output_type -> levee.DiagnosticReportMessage
	7,  // 22: levee.DiagnosisService.GetDiagnosis:output_type -> levee.DiagnosticReportMessage
	10, // 23: levee.ConversationService.SendMessage:output_type -> levee.ReplyMessage
	10, // 24: levee.ConversationService.SubscribeConversation:output_type -> levee.ReplyMessage
	14, // 25: levee.InventoryService.ListGroups:output_type -> levee.ListGroupsResponse
	11, // 26: levee.InventoryService.CreateGroup:output_type -> levee.Group
	16, // 27: levee.InventoryService.DeleteGroup:output_type -> levee.DeleteGroupResponse
	18, // 28: levee.InventoryService.ImportTargets:output_type -> levee.ImportTargetsResponse
	20, // 29: levee.InventoryService.SetTargetStatus:output_type -> levee.SetTargetStatusResponse
	23, // 30: levee.InventoryService.TargetHistory:output_type -> levee.TargetHistoryResponse
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_levee_extra_proto_init() }
func file_levee_extra_proto_init() {
	if File_levee_extra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_levee_extra_proto_rawDesc), len(file_levee_extra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_levee_extra_proto_goTypes,
		DependencyIndexes: file_levee_extra_proto_depIdxs,
		MessageInfos:      file_levee_extra_proto_msgTypes,
	}.Build()
	File_levee_extra_proto = out.File
	file_levee_extra_proto_goTypes = nil
	file_levee_extra_proto_depIdxs = nil
}
